import {
  buildAnalyticsBundle, buildLiveTwinWithScores, computeReputationScore, fetchOrgGoogleWebEvidence, gatherOverviewLiveMetrics,
  getOrganisationBusinessProfile, getScoreValue, healthTrendFromHistory, loadHealthHistory, metricsContextFromLiveMetrics,
  sessionCan, type AnalyticsBundle, type AnalyticsTrendPoint, type GoogleWebEvidence, type OrganisationBusinessProfile,
  type OverviewConnectorProbes, type OverviewLiveMetrics, type ScoreResult,
} from "@dg/platform-core";
import { fetchOverviewConnectorProbes } from "@/lib/overview-connectors";
import { getOrgEnabledAppIds, getPlatformPageContext } from "@/lib/org-apps";
import { loadReviewsSessionAndFeed } from "@/lib/reviews-feed";
export { formatAnalyticsAud as formatAudMoney } from "@dg/platform-core";
export type AnalyticsTwinScores={seo:number;aiVisibility:number;websiteHealth:number;reputation:number;businessHealth:number};
export type AnalyticsInsight={id:string;tone:"positive"|"attention"|"opportunity"|"neutral";title:string;body:string;actionLabel:string;href:string};
export type AnalyticsBreakdown={label:string;value:number};
export type AnalyticsOperationalData={totalLeads:number;qualifiedLeads:number;convertedLeads:number;leadConversionRate:number|null;totalOpportunities:number;openOpportunities:number;wonOpportunities:number;opportunityWinRate:number|null;opportunityPipelineCents:number;weightedPipelineCents:number;contactsCreated30d:number;activities30d:number;tasksOpen:number;tasksOverdue:number;leadSources:AnalyticsBreakdown[];opportunityStages:AnalyticsBreakdown[]};
export type AnalyticsPageData={bundle:AnalyticsBundle;metrics:OverviewLiveMetrics|null;operational:AnalyticsOperationalData|null;google:GoogleWebEvidence|null;insights:AnalyticsInsight[];scoreResults:ScoreResult[];twinScores:AnalyticsTwinScores;healthTrend:number[];connectors:OverviewConnectorProbes;profile:OrganisationBusinessProfile|null;canViewOrganisationFinancials:boolean};
const DEFAULT_TWIN_SCORES={seo:0,aiVisibility:0,websiteHealth:0,reputation:0,businessHealth:0};
function redactFinancialReporting(bundle:AnalyticsBundle):AnalyticsBundle{const dataSources=bundle.dataSources.filter(s=>s.id!=="stripe");return{...bundle,keyMetrics:bundle.keyMetrics.map(m=>m.id==="revenue"?{...m,value:"—",context:"Restricted by your permissions",status:"unavailable",href:undefined}:m),dataSources,connectedSourceCount:dataSources.filter(s=>s.status==="connected").length,predefinedDashboards:bundle.predefinedDashboards.map(d=>d.id==="executive"?{...d,description:"Leads, pipeline, conversion, health and growth",metrics:d.metrics.filter(m=>m!=="Revenue")}:d),reportTemplates:bundle.reportTemplates.map(r=>({...r,sections:r.sections.filter(s=>s!=="Revenue")}))}}
function applyNativeReviewSource(bundle:AnalyticsBundle,feed:{ok:boolean;total:number}){const dataSources=bundle.dataSources.map(s=>s.id!=="reviews"?s:!feed.ok?{...s,status:"not_connected" as const,statusLabel:"Not connected",updatedLabel:"Not connected",detail:"Connect review sources to unlock reputation metrics",href:"/apps/reviews/sources"}:{...s,status:"connected" as const,statusLabel:"Connected",updatedLabel:"Live",detail:`${feed.total} review${feed.total===1?"":"s"} available from connected sources`,href:"/apps/reviews"});return{...bundle,dataSources,connectedSourceCount:dataSources.filter(s=>s.status==="connected").length}}
function applyGoogleAnalyticsSource(bundle:AnalyticsBundle,google:GoogleWebEvidence|null){const dataSources=bundle.dataSources.map(s=>s.id!=="ga"?s:google?.analytics?{...s,status:"connected" as const,statusLabel:"Connected",updatedLabel:"Live",detail:`Google Analytics · ${google.analytics.sessions.toLocaleString("en-AU")} sessions in the last 30 days`,href:"/apps/analytics/connectors/google"}:{...s,href:"/apps/analytics/connectors/google"});return{...bundle,dataSources,connectedSourceCount:dataSources.filter(s=>s.status==="connected").length}}
async function loadLeadHistory(id:string){const{prisma}=await import("@dg/database");const now=new Date(),first=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()-7,1));const months=Array.from({length:8},(_,i)=>{const d=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+i,1));return{key:`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}`,label:d.toLocaleDateString("en-AU",{month:"short",timeZone:"UTC"})}});const leads=await prisma.lead.findMany({where:{organisationId:id,createdAt:{gte:first}},select:{createdAt:true}}),counts=new Map(months.map(m=>[m.key,0]));for(const l of leads){const k=`${l.createdAt.getUTCFullYear()}-${String(l.createdAt.getUTCMonth()+1).padStart(2,"0")}`;if(counts.has(k))counts.set(k,(counts.get(k)??0)+1)}return{points:months.map(m=>({label:m.label,value:counts.get(m.key)??0})),note:leads.length?"Monthly CRM leads created over the last eight months.":"Add leads in CRM to begin building a monthly lead history."}}
async function loadOperationalAnalytics(id:string):Promise<AnalyticsOperationalData>{const{prisma}=await import("@dg/database");const since=new Date(Date.now()-30*86400000),now=new Date();const[leads,opps,contacts,activities,tasks,overdue]=await Promise.all([prisma.lead.findMany({where:{organisationId:id},select:{status:true,source:true}}),prisma.opportunity.findMany({where:{organisationId:id},select:{status:true,stage:true,valueCents:true,probability:true}}),prisma.contact.count({where:{organisationId:id,deletedAt:null,createdAt:{gte:since}}}),prisma.activity.count({where:{organisationId:id,createdAt:{gte:since}}}),prisma.task.count({where:{organisationId:id,status:"open"}}),prisma.task.count({where:{organisationId:id,status:"open",dueAt:{lt:now}}})]);const conv=new Set(["converted","won","closed_won"]),qual=new Set(["qualified","contacted","converted","won","closed_won"]),won=new Set(["won","closed_won"]),open=opps.filter(o=>o.status.toLowerCase()==="open"),lc=new Map<string,number>(),sc=new Map<string,number>();for(const l of leads)lc.set(l.source||"Unknown",(lc.get(l.source||"Unknown")??0)+1);for(const o of open)sc.set(o.stage||"Open",(sc.get(o.stage||"Open")??0)+1);const sort=(m:Map<string,number>)=>[...m.entries()].map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value).slice(0,6),converted=leads.filter(l=>conv.has(l.status.toLowerCase())).length,wins=opps.filter(o=>won.has(o.status.toLowerCase())).length;return{totalLeads:leads.length,qualifiedLeads:leads.filter(l=>qual.has(l.status.toLowerCase())).length,convertedLeads:converted,leadConversionRate:leads.length?Math.round(converted/leads.length*100):null,totalOpportunities:opps.length,openOpportunities:open.length,wonOpportunities:wins,opportunityWinRate:opps.length?Math.round(wins/opps.length*100):null,opportunityPipelineCents:open.reduce((a,o)=>a+(o.valueCents??0),0),weightedPipelineCents:open.reduce((a,o)=>a+Math.round((o.valueCents??0)*((o.probability??0)/100)),0),contactsCreated30d:contacts,activities30d:activities,tasksOpen:tasks,tasksOverdue:overdue,leadSources:sort(lc),opportunityStages:sort(sc)}}
function buildInsights(metrics:OverviewLiveMetrics|null,op:AnalyticsOperationalData|null,scores:AnalyticsTwinScores,count:number,google:GoogleWebEvidence|null){const a:AnalyticsInsight[]=[];if(google?.search&&google.search.impressions>0)a.push({id:"google-search",tone:"opportunity",title:"Google Search demand is measurable",body:`Your site recorded ${google.search.clicks.toLocaleString("en-AU")} clicks from ${google.search.impressions.toLocaleString("en-AU")} Google Search impressions over the last 30 days. Use query evidence to align content and lead-generation priorities.`,actionLabel:"Review Google data",href:"/apps/analytics/connectors/google"});if(google?.analytics&&google.analytics.sessions>0)a.push({id:"google-traffic",tone:"positive",title:"Website traffic is now part of the Business Brain",body:`Google Analytics recorded ${google.analytics.sessions.toLocaleString("en-AU")} sessions and ${google.analytics.activeUsers.toLocaleString("en-AU")} active users over the last 30 days. DigitalGate can now interpret acquisition alongside CRM outcomes.`,actionLabel:"Review Google data",href:"/apps/analytics/connectors/google"});if(!metrics||!op)return a.slice(0,5);if(metrics.overdueFollowUps>0||op.tasksOverdue>0)a.push({id:"follow-up",tone:"attention",title:"Follow-up queue needs attention",body:`${metrics.overdueFollowUps} lead follow-up${metrics.overdueFollowUps===1?" is":"s are"} overdue and ${op.tasksOverdue} task${op.tasksOverdue===1?" is":"s are"} overdue.`,actionLabel:"Open tasks",href:"/apps/crm/tasks"});if(op.openOpportunities>0&&op.weightedPipelineCents>0)a.push({id:"pipeline",tone:"opportunity",title:"Pipeline has forecastable value",body:`${op.openOpportunities} open opportunities carry probability-weighted value.`,actionLabel:"Review opportunities",href:"/apps/crm/opportunities"});if(count<3)a.push({id:"coverage",tone:"neutral",title:"Analytics coverage can be deeper",body:`Only ${count} data sources are currently contributing. Connecting more systems improves attribution and Aida's recommendations.`,actionLabel:"Connect data sources",href:"/apps/analytics/connectors"});return a.slice(0,5)}
export async function loadAnalyticsPageData():Promise<AnalyticsPageData>{const{session:p}=await getPlatformPageContext();const organisationName=p?.organisationName??"Your business";if(!p){const bundle=buildAnalyticsBundle({organisationName});return{bundle,metrics:null,operational:null,google:null,insights:[],scoreResults:[],twinScores:DEFAULT_TWIN_SCORES,healthTrend:[],connectors:{},profile:null,canViewOrganisationFinancials:false}}const can=sessionCan(p,{module:"commerce",action:"view",scope:"organisation"}),enabled=await getOrgEnabledAppIds();const[metrics,operational,connectors,profile,history,reviews,leadHistory,googleResult]=await Promise.all([gatherOverviewLiveMetrics(p.organisationId,{includeFinancials:can}),loadOperationalAnalytics(p.organisationId),fetchOverviewConnectorProbes(enabled,p.organisationId),getOrganisationBusinessProfile(p.organisationId),loadHealthHistory(p.organisationId),loadReviewsSessionAndFeed(),loadLeadHistory(p.organisationId),fetchOrgGoogleWebEvidence(p.organisationId)]);const google=googleResult.ok?googleResult.data:null;let scoreResults:ScoreResult[]=[],twinScores:AnalyticsTwinScores=DEFAULT_TWIN_SCORES,twinResult=null;const reputation=computeReputationScore(reviews.feed);if(metrics){const{scores}=buildLiveTwinWithScores({organisationId:p.organisationId,organisationName:p.organisationName,enabledAppIds:enabled,metrics,connectors,profile,metricsContext:metricsContextFromLiveMetrics(metrics),reputationOverride:reputation.score});twinResult=scores;scoreResults=scores.scores;twinScores={seo:getScoreValue(scores.scores,"seo"),aiVisibility:getScoreValue(scores.scores,"ai_visibility"),websiteHealth:getScoreValue(scores.scores,"website_health"),reputation:reputation.score??0,businessHealth:scores.businessHealth}}const healthTrend=healthTrendFromHistory(history,twinScores.businessHealth),base={...buildAnalyticsBundle({organisationName,metrics,connectors,scores:twinResult,reputationScore:reputation.score,profile}),leadTrend:leadHistory.points,leadTrendNote:leadHistory.note},native=applyNativeReviewSource(base,{ok:reviews.feedStatus.ok,total:reviews.feedStatus.total}),withGoogle=applyGoogleAnalyticsSource(native,google),bundle=can?withGoogle:redactFinancialReporting(withGoogle),insights=buildInsights(metrics,operational,twinScores,bundle.connectedSourceCount,google);return{bundle,metrics,operational,google,insights,scoreResults,twinScores,healthTrend,connectors,profile,canViewOrganisationFinancials:can}}
