export type ServicesWorkspaceProfile = {
  title: string;
  description: string;
  eyebrow: string;
  capabilityHeading: string;
  capabilityIntro: string;
  capabilities: Array<[string, string]>;
};

export const SERVICES_WORKSPACE_PROFILES: Record<string, ServicesWorkspaceProfile> = {
  electrician: {
    title: "Electrical",
    description: "Electrical estimating, scheduling, field work, compliance and recurring service operations.",
    eyebrow: "Electrical operations",
    capabilityHeading: "Run electrical work from enquiry to certificate",
    capabilityIntro: "Keep quotes, jobs, technicians, site details, testing, compliance evidence and recurring electrical maintenance together.",
    capabilities: [
      ["Quotes & estimates", "Labour, materials, call-outs and project estimates linked to the customer."],
      ["Jobs & dispatch", "Schedule electricians, allocate work and track progress in the field."],
      ["Site & switchboard notes", "Keep access, meter, switchboard and installation details with the job."],
      ["Testing & compliance", "Capture test results, certificates, compliance notes and required evidence."],
      ["Materials & equipment", "Record parts, fittings, equipment and items required for each job."],
      ["Recurring servicing", "Plan preventative electrical inspections and recurring service visits."],
      ["Photos & proof", "Store before/after evidence, defects and completion records."],
      ["Job profitability", "Connect labour, materials, quotes and invoices to understand job performance."],
    ],
  },
  plumber: {
    title: "Plumbing",
    description: "Plumbing quoting, dispatch, emergency call-outs, field capture, materials and compliance.",
    eyebrow: "Plumbing operations",
    capabilityHeading: "Run plumbing work from call-out to completion",
    capabilityIntro: "Coordinate urgent and planned jobs, technicians, site access, assets, parts, compliance and customer approvals.",
    capabilities: [
      ["Emergency dispatch", "Prioritise urgent leaks, blockages, hot-water failures and call-outs."],
      ["Quotes & approvals", "Create estimates and capture customer approval before additional work."],
      ["Jobs & scheduling", "Allocate plumbers, schedule visits and manage return visits."],
      ["Site & asset history", "Keep property, fixture, hot-water and meter history together."],
      ["Parts & materials", "Track required parts, fittings and materials against each job."],
      ["Compliance", "Record permits, gas/plumbing compliance notes and certificates."],
      ["Photos & diagnosis", "Capture faults, before/after photos and technician notes."],
      ["Recurring maintenance", "Schedule preventative servicing for commercial and managed-property clients."],
    ],
  },
  cleaner: {
    title: "Commercial Cleaning",
    description: "Commercial cleaning operations, recurring services, site teams and quality assurance.",
    eyebrow: "Cleaning operations",
    capabilityHeading: "Run every client site from one workspace",
    capabilityIntro: "Structure recurring contracts around sites, scopes of work, areas and zones, assigned teams, access instructions, WHS requirements, chemicals/SDS, equipment, consumables, proof of service and QA inspections.",
    capabilities: [
      ["Sites & contracts", "Client sites, scopes, frequencies and recurring service requirements."],
      ["Teams & shifts", "Assign cleaners and supervisors to scheduled site services."],
      ["Checklists & proof", "Site tasks, completion evidence, photos and exception notes."],
      ["QA & compliance", "Inspections, quality issues, WHS, chemicals/SDS and incidents."],
      ["Consumables", "Track restocking requirements and site consumable needs."],
      ["Equipment", "Record equipment required for each site or service."],
      ["Client requests", "Capture additional service requests and issues against the client/site."],
      ["Site profitability", "Connect services, labour, proposals and billing for contract performance."],
    ],
  },
  maintenance: {
    title: "Property & Facility Maintenance",
    description: "Reactive and planned maintenance, work orders, sites, assets, contractors and service history.",
    eyebrow: "Maintenance operations",
    capabilityHeading: "Control reactive and planned maintenance end to end",
    capabilityIntro: "Manage requests, priorities, SLAs, sites, assets, technicians, subcontractors, parts, compliance, proof of work and recurring preventative maintenance.",
    capabilities: [
      ["Work orders", "Capture reactive requests, planned works, priorities, approvals and status."],
      ["Sites & assets", "Maintain service history by property, venue, room, plant or equipment asset."],
      ["Planned maintenance", "Schedule recurring inspections and preventative maintenance by due date."],
      ["Technicians & contractors", "Assign internal staff or subcontractors and record inductions/licences."],
      ["SLA & priority", "Triage critical, urgent and routine work against agreed response targets."],
      ["Parts & purchasing", "Record materials, parts, supplier requirements and items awaiting delivery."],
      ["WHS & compliance", "Capture hazards, permits, compliance requirements, incidents and sign-off."],
      ["Asset & job profitability", "Connect labour, materials, contractors, quotes and invoices to performance."],
    ],
  },
  builder: {
    title: "Building & Construction",
    description: "Estimates, projects, stages, trades, variations, milestones and customer communication.",
    eyebrow: "Construction operations",
    capabilityHeading: "Keep every project, trade and variation under control",
    capabilityIntro: "Coordinate enquiries, estimates, site work, subcontractors, project stages, variations, approvals, documents and financial progress.",
    capabilities: [
      ["Estimates & proposals", "Scope labour, materials, trades and allowances before approval."],
      ["Projects & stages", "Track construction work through milestones and site stages."],
      ["Subcontractors", "Coordinate trades, scopes, schedules, licences and site requirements."],
      ["Variations", "Record requested changes, pricing, approvals and impact on delivery."],
      ["Site documentation", "Keep plans, photos, permits, safety and client documents together."],
      ["Materials & procurement", "Track materials, suppliers, lead times and site requirements."],
      ["Progress & client updates", "Maintain milestones, completion evidence and customer communication."],
      ["Project profitability", "Connect quoted value, labour, materials, variations and invoices."],
    ],
  },
  hvac: {
    title: "HVAC & Refrigeration",
    description: "Installations, breakdowns, asset servicing, maintenance schedules and compliance.",
    eyebrow: "HVAC operations",
    capabilityHeading: "Manage HVAC assets across their whole service life",
    capabilityIntro: "Run installs and breakdowns while keeping equipment registers, service intervals, technicians, refrigerant/compliance information and maintenance history attached to each site.",
    capabilities: [
      ["Assets & equipment", "Record make, model, serial, location and service history."],
      ["Breakdowns & call-outs", "Triage faults and dispatch technicians quickly."],
      ["Preventative maintenance", "Schedule recurring servicing by asset and contract."],
      ["Installations", "Manage site assessment, quotation, equipment and commissioning."],
      ["Compliance", "Capture licences, refrigerant/compliance notes and commissioning records."],
      ["Parts & refrigerant", "Record parts, consumables and materials required for service work."],
      ["Technician evidence", "Keep readings, diagnosis, photos and completion notes."],
      ["Contract profitability", "Compare service revenue, labour, parts and asset maintenance cost."],
    ],
  },
  landscaper: {
    title: "Landscaping & Grounds",
    description: "Quoting, projects, recurring visits, crews, materials and grounds maintenance.",
    eyebrow: "Landscaping operations",
    capabilityHeading: "Run projects and recurring grounds work together",
    capabilityIntro: "Manage site visits, landscape projects, maintenance rounds, crews, materials, client requests and recurring property service schedules.",
    capabilities: [
      ["Sites & rounds", "Group recurring maintenance visits by property and service frequency."],
      ["Projects", "Manage landscape builds, stages, crews and completion milestones."],
      ["Quotes", "Estimate labour, plants, materials, machinery and subcontractors."],
      ["Crews & scheduling", "Allocate teams, vehicles and equipment to site work."],
      ["Materials", "Track plants, soil, mulch, hardscape products and consumables."],
      ["Photos & site notes", "Capture condition, completed work and customer requests."],
      ["Seasonal tasks", "Plan recurring mowing, pruning, irrigation and seasonal maintenance."],
      ["Site profitability", "Measure recurring and project work against labour and material cost."],
    ],
  },
  pest_control: {
    title: "Pest Control",
    description: "Bookings, routes, treatments, compliance, recurring visits and customer history.",
    eyebrow: "Pest-control operations",
    capabilityHeading: "Manage treatments, compliance and recurring pest programmes",
    capabilityIntro: "Coordinate inspections, treatments, technicians, chemicals, service areas, evidence, recommendations and future treatment schedules.",
    capabilities: [
      ["Inspections", "Capture pest activity, risk areas, findings and treatment recommendations."],
      ["Treatments", "Record service type, areas treated, products and technician notes."],
      ["Routes & scheduling", "Plan technician appointments and recurring service runs."],
      ["Chemical compliance", "Maintain product, SDS, usage and safety information."],
      ["Photos & evidence", "Record pest evidence, treatment areas and completion proof."],
      ["Recurring programmes", "Schedule termite, rodent and general pest follow-ups."],
      ["Customer history", "Keep prior treatments, recommendations and service outcomes together."],
      ["Service profitability", "Connect labour, chemicals, quotes and invoices to each visit."],
    ],
  },
  painter: {
    title: "Painting",
    description: "Estimating, rooms and areas, colours, materials, crews and progress tracking.",
    eyebrow: "Painting operations",
    capabilityHeading: "Control every painting job from measure-up to handover",
    capabilityIntro: "Manage estimates, surfaces, colours, preparation, materials, crews, access, progress photos, defects and final sign-off.",
    capabilities: [
      ["Measure & estimate", "Scope rooms, areas, surfaces, coats, labour and materials."],
      ["Colours & specifications", "Store paint systems, colours, finishes and client selections."],
      ["Crews & scheduling", "Coordinate painters, access and project sequencing."],
      ["Preparation", "Track repairs, masking, sanding, priming and surface preparation."],
      ["Materials", "Record paint, consumables, equipment and supplier requirements."],
      ["Progress photos", "Capture before, during and completed work."],
      ["Defects & touch-ups", "Manage punch lists and final rectification."],
      ["Job profitability", "Compare quoted labour/materials with actual job performance."],
    ],
  },
  handyman: {
    title: "Handyman & General Maintenance",
    description: "Multi-trade repairs, small jobs, property tasks, scheduling and materials.",
    eyebrow: "Handyman operations",
    capabilityHeading: "Keep varied property jobs organised without the paperwork",
    capabilityIntro: "Handle mixed repair requests, site access, materials, scheduling, photos, customer approvals and recurring property maintenance from one queue.",
    capabilities: [
      ["Job requests", "Capture varied repairs and maintenance tasks with priority and site details."],
      ["Quotes & approvals", "Price small works and obtain approval before proceeding."],
      ["Scheduling", "Plan visits and group multiple tasks at the same property."],
      ["Materials", "Track hardware, consumables and parts needed for each visit."],
      ["Site history", "See previous repairs and outstanding issues by property."],
      ["Photos & proof", "Capture before/after evidence and completion notes."],
      ["Recurring tasks", "Schedule routine property and preventative maintenance."],
      ["Job profitability", "Understand labour, materials and margin on small works."],
    ],
  },
  solar: {
    title: "Solar & Energy",
    description: "Site assessments, proposals, installations, commissioning, assets and maintenance.",
    eyebrow: "Solar operations",
    capabilityHeading: "Manage solar projects from assessment through ongoing service",
    capabilityIntro: "Coordinate site assessment, system design, proposals, installation, equipment, compliance, commissioning and maintenance history.",
    capabilities: [
      ["Site assessment", "Capture roof, switchboard, usage and installation constraints."],
      ["System proposal", "Record system size, panels, inverter, batteries and pricing."],
      ["Installation", "Schedule crews, equipment and project milestones."],
      ["Equipment register", "Keep serials, warranties and installed assets against the site."],
      ["Compliance", "Track approvals, certificates, commissioning and connection requirements."],
      ["Photos & commissioning", "Capture installation evidence and handover records."],
      ["Service & warranty", "Manage faults, warranty cases and preventative checks."],
      ["Project profitability", "Connect equipment, labour, proposal and invoice performance."],
    ],
  },
  pool_service: {
    title: "Pool Service",
    description: "Recurring pool servicing, water testing, chemicals, equipment and repairs.",
    eyebrow: "Pool-service operations",
    capabilityHeading: "Run recurring pool routes and equipment service together",
    capabilityIntro: "Manage customer pools, service frequencies, water readings, chemical dosing, equipment, repairs, technician routes and service history.",
    capabilities: [
      ["Pools & equipment", "Record pool details, pumps, filters, chlorinators and equipment history."],
      ["Service routes", "Schedule recurring technicians and efficient weekly service rounds."],
      ["Water readings", "Capture chemistry readings, actions and treatment notes."],
      ["Chemicals", "Record dosing, products and consumables used at each service."],
      ["Repairs", "Create work orders for failed equipment and customer approvals."],
      ["Photos & proof", "Capture condition, readings and completion evidence."],
      ["Recurring plans", "Manage weekly, fortnightly and seasonal service programmes."],
      ["Route profitability", "Compare recurring revenue with labour, chemicals and repair work."],
    ],
  },
  general: {
    title: "Services",
    description: "Flexible field-service operations for businesses without a specialised profile yet.",
    eyebrow: "Services operations",
    capabilityHeading: "Run enquiries, jobs, scheduling and customers in one place",
    capabilityIntro: "Use the shared Services engine now, then add a specialised business type when you want tailored workflows and terminology.",
    capabilities: [
      ["Jobs", "Manage field work from enquiry through completion."],
      ["Scheduling", "Allocate people and dates to upcoming work."],
      ["Customers", "Keep service history connected to CRM records."],
      ["Quotes", "Connect estimates and approvals to operational work."],
      ["Notes & photos", "Capture field evidence and job history."],
      ["Teams", "Coordinate staff and assignment."],
      ["Recurring work", "Represent repeat service requirements."],
      ["Reporting", "Keep operational activity connected to platform analytics."],
    ],
  },
};

export function getServicesWorkspaceProfile(templateKey?: string | null): ServicesWorkspaceProfile {
  if (templateKey && SERVICES_WORKSPACE_PROFILES[templateKey]) return SERVICES_WORKSPACE_PROFILES[templateKey];
  return SERVICES_WORKSPACE_PROFILES.general;
}
