/**
 * Gen 2 canonical customer onboarding journey.
 * The journey persists the business operating profile and platform preparation
 * so navigation, resume and downstream personalisation share one source of truth.
 */
export const GEN2_ONBOARDING_STEPS = ["welcome", "business_identity", "operating_profile", "business_profile", "goals", "plan", "apps", "support", "platform_preparation", "billing_cadence", "order_summary", "stripe", "connect", "checklist", "implementation"] as const;
export type Gen2OnboardingStep = (typeof GEN2_ONBOARDING_STEPS)[number];
export const GEN2_ONBOARDING_STEP_LABELS: Record<Gen2OnboardingStep, string> = { welcome: "Welcome", business_identity: "Business identity", operating_profile: "Operating Profile", business_profile: "Business Profile", goals: "Goals & priorities", plan: "Platform plan", apps: "Apps", support: "Support", platform_preparation: "Platform Preparation", billing_cadence: "Monthly or annual", order_summary: "Your DigitalGate setup", stripe: "Activate subscription", connect: "Connect your business", checklist: "Getting started", implementation: "Implementation" };
export type BillingCadence = "monthly" | "annual";
export type Gen2PlatformTier = "starter" | "professional" | "business";
export type Gen2SupportPlan = "self_managed" | "guided" | "managed" | "custom";
export type Gen2PlatformAppearance = "dark" | "light" | "system";
export type Gen2ConnectionProvider = "google_workspace" | "microsoft_365" | "apple_icloud";
export type Gen2ConnectionCapability = "contacts" | "calendar" | "mail";
export type Gen2VipSetup = {
  version: 1; required?: boolean; completedAt?: string | null; rerunRequestedAt?: string | null; firstLoginHandoverCompletedAt?: string | null;
  appearance: Gen2PlatformAppearance; timezone: string; locale: string; currency: string;
  websiteDomain?: string; websiteMigrationIntent?: "migrate" | "replace" | "connect" | "none";
  brandPrimary?: string; brandAccent?: string; brandColoursExtracted?: boolean; brandColoursOverridden?: boolean;
  socialProfiles?: Record<string, string>; contactImportRequested?: boolean; contactImportFormat?: "csv" | "vcard";
  connections?: Partial<Record<Gen2ConnectionProvider, { requested: boolean; requestedCapabilities: Gen2ConnectionCapability[]; status: "not_started" | "planned" | "connected" | "attention_required" }>>;
  aiAdvicePriorities?: string[]; aiReportingPriorities?: string[];
};
export type Gen2OperatingProfile = { primaryIndustry?: string; secondaryIndustries?: string[]; primaryTemplate?: string; templates?: string[]; recommendedIndustryApps?: string[]; recommendedGrowthApps?: string[]; recommendedWorkflows?: string[]; recommendedDashboard?: string[]; };
export type Gen2JourneyPosition = { stage?: Gen2OnboardingStep; substep?: string; updatedAt?: string };
export type Gen2OnboardingProgress = { version: 1; currentStep: Gen2OnboardingStep; completedSteps: Gen2OnboardingStep[]; startedAt: string; updatedAt: string; completedAt?: string | null; platformTier?: Gen2PlatformTier; industryApps?: string[]; industryTemplates?: string[]; premiumApps?: string[]; supportPlan?: Gen2SupportPlan; billingCadence?: BillingCadence; stripeCheckoutSessionId?: string | null; subscriptionActivatedAt?: string | null; checklist?: Record<string, boolean>; founding?: boolean; vipSetup?: Gen2VipSetup; operatingProfile?: Gen2OperatingProfile; journeyPosition?: Gen2JourneyPosition; };
export const GEN2_CHECKLIST_ITEMS = [
  { id: "business_identity", label: "Business identity", step: "business_identity" as const }, { id: "operating_profile", label: "Operating Profile", step: "operating_profile" as const }, { id: "business_profile", label: "Business Profile", step: "business_profile" as const }, { id: "goals", label: "Goals", step: "goals" as const }, { id: "plan", label: "Plan selected", step: "plan" as const }, { id: "apps", label: "Apps selected", step: "apps" as const }, { id: "support", label: "Support selected", step: "support" as const }, { id: "platform_preparation", label: "Platform Preparation", step: "platform_preparation" as const }, { id: "subscription", label: "Subscription activated", step: "stripe" as const }, { id: "connect_website", label: "Connect website", optional: true }, { id: "connect_google", label: "Connect Google", optional: true }, { id: "import_contacts", label: "Import contacts", optional: true }, { id: "configure_apps", label: "Configure Apps", optional: true }, { id: "review_brain", label: "Review Business Brain", optional: true }, { id: "implementation", label: "Implementation complete", step: "implementation" as const },
] as const;
export const GEN2_PLATFORM_PLANS: Array<{ id: Gen2PlatformTier; name: string; monthlyCents: number; blurb: string }> = [ { id: "starter", name: "Starter", monthlyCents: 9900, blurb: "Core CRM, communications, documents and website foundation." }, { id: "professional", name: "Growth", monthlyCents: 24900, blurb: "Full Business Operating Platform for growing teams." }, { id: "business", name: "Scale", monthlyCents: 49900, blurb: "Scale operations with higher capacity and priority support." } ];
export const GEN2_SUPPORT_PLANS: Array<{ id: Gen2SupportPlan; name: string; blurb: string; detail: string }> = [
  { id: "self_managed", name: "Self-Managed", blurb: "Run DigitalGate yourself.", detail: "Platform access, Aida, knowledge base and standard support." },
  { id: "guided", name: "Guided", blurb: "Help when you need it.", detail: "Setup assistance, priority support and optimisation guidance." },
  { id: "managed", name: "Managed", blurb: "We help operate it with you.", detail: "Hands-on integrations, automation management and ongoing optimisation." },
  { id: "custom", name: "Custom", blurb: "DigitalGate becomes part of the operation.", detail: "Tailored managed services, integrations, development or consulting." },
];
export const GEN2_GOAL_OPTIONS = [ { id: "more_leads", label: "Generate more leads" }, { id: "website_performance", label: "Improve website performance" }, { id: "seo", label: "Improve SEO" }, { id: "ai_visibility", label: "Improve AI visibility" }, { id: "manage_customers", label: "Manage customers" }, { id: "automate_followup", label: "Automate follow-up" }, { id: "manage_jobs", label: "Manage jobs" }, { id: "manage_property", label: "Manage property" }, { id: "manage_bookings", label: "Manage bookings" }, { id: "reputation", label: "Improve reputation" }, { id: "operational_efficiency", label: "Improve operational efficiency" } ] as const;
export function isGen2OnboardingStep(value: unknown): value is Gen2OnboardingStep { return typeof value === "string" && (GEN2_ONBOARDING_STEPS as readonly string[]).includes(value); }
export function nextGen2Step(step: Gen2OnboardingStep): Gen2OnboardingStep | null { const i = GEN2_ONBOARDING_STEPS.indexOf(step); if (i < 0 || i >= GEN2_ONBOARDING_STEPS.length - 1) return null; return GEN2_ONBOARDING_STEPS[i + 1]!; }
export function gen2ChecklistStats(progress: Gen2OnboardingProgress | null) { const completed = new Set(progress?.completedSteps ?? []); const extra = progress?.checklist ?? {}; let done = 0; for (const item of GEN2_CHECKLIST_ITEMS) { if ("step" in item && item.step && completed.has(item.step)) { done += 1; continue; } if (extra[item.id]) done += 1; } return { done, total: GEN2_CHECKLIST_ITEMS.length }; }
export function emptyGen2Progress(founding = false): Gen2OnboardingProgress { const now = new Date().toISOString(); return { version: 1, currentStep: "welcome", completedSteps: [], startedAt: now, updatedAt: now, completedAt: null, platformTier: "professional", industryApps: [], industryTemplates: [], premiumApps: [], supportPlan: "self_managed", billingCadence: "monthly", founding, checklist: {}, operatingProfile: { secondaryIndustries: [], templates: [], recommendedIndustryApps: [], recommendedGrowthApps: [], recommendedWorkflows: [], recommendedDashboard: [] }, journeyPosition: { stage: "welcome", updatedAt: now }, vipSetup: { version: 1, appearance: "system", timezone: "Australia/Brisbane", locale: "en-AU", currency: "AUD", connections: {}, firstLoginHandoverCompletedAt: null } }; }