import { getOrgConnectorSettings, saveOrgConnectorSettings } from "../framework/store";
import { ensureValidOrgGoogleAccessToken, googleApiGet } from "./auth";
export type GoogleAnalyticsProperty={name:string;displayName:string;account?:string;timeZone?:string;currencyCode?:string}; export type GoogleSearchConsoleSite={siteUrl:string;permissionLevel?:string}; export type OrgGoogleAnalyticsSettings={property?:string;propertyLabel?:string;searchConsoleSite?:string;updatedAt?:string};
export type GoogleWebEvidence={analytics?:{activeUsers:number;sessions:number;engagedSessions:number;keyEvents:number;channels:Array<{channel:string;sessions:number}>};search?:{clicks:number;impressions:number;ctr:number;position:number;queries:Array<{query:string;clicks:number;impressions:number;position:number}>};period:string};
export async function getOrgGoogleAnalyticsSettings(id:string):Promise<OrgGoogleAnalyticsSettings>{const b=await getOrgConnectorSettings(id,"google-analytics");if(!b)return{};return{property:typeof b.property==="string"?b.property:undefined,propertyLabel:typeof b.propertyLabel==="string"?b.propertyLabel:undefined,searchConsoleSite:typeof b.searchConsoleSite==="string"?b.searchConsoleSite:undefined,updatedAt:typeof b.updatedAt==="string"?b.updatedAt:undefined}}
export async function saveOrgGoogleAnalyticsSettings(id:string,s:OrgGoogleAnalyticsSettings){await saveOrgConnectorSettings(id,"google-analytics",{...s,updatedAt:new Date().toISOString()})}
export async function discoverOrgGoogleAnalyticsProperties(id:string):Promise<{ok:true;properties:GoogleAnalyticsProperty[]}|{ok:false;message:string}>{const t=await ensureValidOrgGoogleAccessToken(id);if(!t.ok)return t;const a=await googleApiGet("https://analyticsadmin.googleapis.com/v1beta/accountSummaries?pageSize=200",t.accessToken);if(!a.ok)return{ok:false,message:a.message};const s=a.data&&typeof a.data==="object"&&"accountSummaries" in a.data?(a.data as {accountSummaries?:Array<{account?:string;propertySummaries?:Array<{property?:string;displayName?:string}>}>}).accountSummaries??[]:[];return{ok:true,properties:s.flatMap(x=>(x.propertySummaries??[]).filter(p=>p.property).map(p=>({name:p.property!,displayName:p.displayName||p.property!,account:x.account})))}}
export async function discoverOrgGoogleSearchConsoleSites(id:string):Promise<{ok:true;sites:GoogleSearchConsoleSite[]}|{ok:false;message:string}>{const t=await ensureValidOrgGoogleAccessToken(id);if(!t.ok)return t;const r=await googleApiGet("https://www.googleapis.com/webmasters/v3/sites",t.accessToken);if(!r.ok)return{ok:false,message:r.message};return{ok:true,sites:r.data&&typeof r.data==="object"&&"siteEntry" in r.data?((r.data as {siteEntry?:GoogleSearchConsoleSite[]}).siteEntry??[]):[]}}
async function post(url:string,token:string,body:unknown){const r=await fetch(url,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(body)});const text=await r.text();let data:unknown=null;try{data=text?JSON.parse(text):null}catch{data=text}return r.ok?{ok:true as const,data}:{ok:false as const,message:`Google API HTTP ${r.status}`}}
const n=(v?:string)=>Number.isFinite(Number(v))?Number(v):0;
export async function fetchOrgGoogleWebEvidence(id:string):Promise<{ok:true;data:GoogleWebEvidence}|{ok:false;message:string}>{const s=await getOrgGoogleAnalyticsSettings(id);if(!s.property&&!s.searchConsoleSite)return{ok:false,message:"Google Analytics and Search Console are not configured"};const t=await ensureValidOrgGoogleAccessToken(id);if(!t.ok)return t;const out:GoogleWebEvidence={period:"Last 30 days"};
if(s.property){const pid=s.property.replace(/^properties\//,"");const r=await post(`https://analyticsdata.googleapis.com/v1beta/properties/${encodeURIComponent(pid)}:runReport`,t.accessToken,{dateRanges:[{startDate:"30daysAgo",endDate:"today"}],dimensions:[{name:"sessionDefaultChannelGroup"}],metrics:[{name:"activeUsers"},{name:"sessions"},{name:"engagedSessions"},{name:"keyEvents"}],orderBys:[{metric:{metricName:"sessions"},desc:true}],limit:10});if(r.ok){const rows=r.data&&typeof r.data==="object"&&"rows" in r.data?(r.data as {rows?:Array<{dimensionValues?:Array<{value?:string}>;metricValues?:Array<{value?:string}>}>}).rows??[]:[];out.analytics={activeUsers:rows.reduce((a,x)=>a+n(x.metricValues?.[0]?.value),0),sessions:rows.reduce((a,x)=>a+n(x.metricValues?.[1]?.value),0),engagedSessions:rows.reduce((a,x)=>a+n(x.metricValues?.[2]?.value),0),keyEvents:rows.reduce((a,x)=>a+n(x.metricValues?.[3]?.value),0),channels:rows.slice(0,6).map(x=>({channel:x.dimensionValues?.[0]?.value||"Unassigned",sessions:n(x.metricValues?.[1]?.value)}))}}}
if(s.searchConsoleSite){const end=new Date(),start=new Date(Date.now()-30*86400000),iso=(d:Date)=>d.toISOString().slice(0,10);const r=await post(`https://www.googleapis.com/webmasters/v3/sites/${encodeURIComponent(s.searchConsoleSite)}/searchAnalytics/query`,t.accessToken,{startDate:iso(start),endDate:iso(end),dimensions:["query"],rowLimit:25});if(r.ok){const rows=r.data&&typeof r.data==="object"&&"rows" in r.data?(r.data as {rows?:Array<{keys?:string[];clicks?:number;impressions?:number;ctr?:number;position?:number}>}).rows??[]:[];const clicks=rows.reduce((a,x)=>a+(x.clicks??0),0),impressions=rows.reduce((a,x)=>a+(x.impressions??0),0);out.search={clicks,impressions,ctr:impressions?clicks/impressions:0,position:impressions?rows.reduce((a,x)=>a+(x.position??0)*(x.impressions??0),0)/impressions:0,queries:rows.slice(0,10).map(x=>({query:x.keys?.[0]||"",clicks:x.clicks??0,impressions:x.impressions??0,position:x.position??0}))}}}
return{ok:true,data:out}}
