import { ensureValidOrgGoogleAccessToken, getOrgGoogleGbpConnectorTokens, googleApiGet, saveOrgGoogleGbpConnectorTokens } from "./auth";

export type YouTubeChannelEvidence={id:string;title:string;description?:string;customUrl?:string;publishedAt?:string;thumbnailUrl?:string;subscribers:number|null;views:number|null;videos:number|null};

export async function probeOrgYouTubeChannels(org:string){
 const ensured=await ensureValidOrgGoogleAccessToken(org);if(!ensured.ok)return ensured;
 const r=await googleApiGet("https://www.googleapis.com/youtube/v3/channels?part=snippet,statistics&mine=true",ensured.accessToken);if(!r.ok)return r;
 const items=r.data&&typeof r.data==="object"&&Array.isArray((r.data as any).items)?(r.data as any).items:[];
 const data:YouTubeChannelEvidence[]=items.flatMap((x:any)=>x?.id?[{id:String(x.id),title:String(x.snippet?.title||x.id),description:typeof x.snippet?.description==="string"?x.snippet.description:undefined,customUrl:typeof x.snippet?.customUrl==="string"?x.snippet.customUrl:undefined,publishedAt:typeof x.snippet?.publishedAt==="string"?x.snippet.publishedAt:undefined,thumbnailUrl:typeof x.snippet?.thumbnails?.default?.url==="string"?x.snippet.thumbnails.default.url:undefined,subscribers:x.statistics?.hiddenSubscriberCount?null:Number.isFinite(Number(x.statistics?.subscriberCount))?Number(x.statistics.subscriberCount):null,views:Number.isFinite(Number(x.statistics?.viewCount))?Number(x.statistics.viewCount):null,videos:Number.isFinite(Number(x.statistics?.videoCount))?Number(x.statistics.videoCount):null}]:[]);
 const tokens=await getOrgGoogleGbpConnectorTokens(org);const allowed=new Set(data.map(x=>x.id)),selectedYouTubeChannelIds=(tokens?.selectedYouTubeChannelIds||[]).filter(id=>allowed.has(id));if(tokens)await saveOrgGoogleGbpConnectorTokens(org,{...tokens,selectedYouTubeChannelIds});return {ok:true as const,data,selectedYouTubeChannelIds};
}
export async function selectOrgYouTubeChannels(org:string,ids:string[]){const p=await probeOrgYouTubeChannels(org);if(!p.ok)return p;const allowed=new Set(p.data.map(x=>x.id)),selectedYouTubeChannelIds=[...new Set(ids)].filter(id=>allowed.has(id));const t=await getOrgGoogleGbpConnectorTokens(org);if(!t)return {ok:false as const,message:"Google is not connected for this organisation"};await saveOrgGoogleGbpConnectorTokens(org,{...t,selectedYouTubeChannelIds});return {ok:true as const,selectedYouTubeChannelIds}}

export type YouTubeVideoEvidence={id:string;title:string;description?:string;publishedAt?:string;thumbnailUrl?:string;views:number|null;likes:number|null;comments:number|null};
export type YouTubeContentEvidence={channel:YouTubeChannelEvidence;videos:YouTubeVideoEvidence[]};
export async function fetchOrgYouTubeContentEvidence(org:string):Promise<{ok:true;data:YouTubeContentEvidence[]}|{ok:false;message:string}>{
 const ensured=await ensureValidOrgGoogleAccessToken(org);if(!ensured.ok)return ensured;const channels=await probeOrgYouTubeChannels(org);if(!channels.ok)return channels;
 const selected=new Set(channels.selectedYouTubeChannelIds||[]),chosen=channels.data.filter(x=>selected.has(x.id));if(!chosen.length)return {ok:false,message:"No YouTube channel is selected for this organisation"};const out:YouTubeContentEvidence[]=[];
 for(const channel of chosen){const search=await googleApiGet(`https://www.googleapis.com/youtube/v3/search?part=snippet&channelId=${encodeURIComponent(channel.id)}&type=video&order=date&maxResults=20`,ensured.accessToken);if(!search.ok)return search;const items=search.data&&typeof search.data==="object"&&Array.isArray((search.data as any).items)?(search.data as any).items:[],ids=items.map((x:any)=>x?.id?.videoId).filter((x:any):x is string=>typeof x==="string");let stats=new Map<string,any>();if(ids.length){const vr=await googleApiGet(`https://www.googleapis.com/youtube/v3/videos?part=snippet,statistics&id=${encodeURIComponent(ids.join(","))}`,ensured.accessToken);if(!vr.ok)return vr;const rows=vr.data&&typeof vr.data==="object"&&Array.isArray((vr.data as any).items)?(vr.data as any).items:[];stats=new Map(rows.map((x:any)=>[String(x.id),x]));}const videos:YouTubeVideoEvidence[]=ids.flatMap((id:string)=>{const x=stats.get(id);if(!x)return [];return [{id,title:String(x.snippet?.title||id),description:typeof x.snippet?.description==="string"?x.snippet.description:undefined,publishedAt:typeof x.snippet?.publishedAt==="string"?x.snippet.publishedAt:undefined,thumbnailUrl:typeof x.snippet?.thumbnails?.medium?.url==="string"?x.snippet.thumbnails.medium.url:undefined,views:Number.isFinite(Number(x.statistics?.viewCount))?Number(x.statistics.viewCount):null,likes:Number.isFinite(Number(x.statistics?.likeCount))?Number(x.statistics.likeCount):null,comments:Number.isFinite(Number(x.statistics?.commentCount))?Number(x.statistics.commentCount):null}]});out.push({channel,videos})}
 return {ok:true,data:out};
}
