import { buildMetaInsightsAuthorizeUrl, metaCredentialsConfigured } from "@dg/platform-core";
import { auth, currentUser } from "@clerk/nextjs/server";
import { NextResponse } from "next/server";
import { resolveActivePlatformSession } from "@/lib/active-platform-session";
import { tenantWriteEntitlementBlock, writeEntitlementResponse } from "@/lib/write-entitlement";
import { fetchPortalMe } from "@/lib/dg-api";
import { createMetaOAuthState } from "@/lib/meta-oauth-state";
export const dynamic="force-dynamic";
export async function GET(req:Request){const appUrl=process.env.NEXT_PUBLIC_APP_URL?.trim()||new URL(req.url).origin||"https://app.digitalgate.com.au";const {userId}=await auth();if(!userId)return NextResponse.redirect(new URL("/login",appUrl));if(!metaCredentialsConfigured())return NextResponse.json({error:{code:"meta_not_configured",message:"META_APP_ID / META_APP_SECRET missing on this deployment"}},{status:503});const user=await currentUser();const email=user?.primaryEmailAddress?.emailAddress??"";const name=user?.fullName??[user?.firstName,user?.lastName].filter(Boolean).join(" ")??email;const portal=email?await fetchPortalMe(email,user?.id):null;const session=await resolveActivePlatformSession({clerkUserId:userId,email,name,orgName:portal?.org_name});if(!session)return NextResponse.json({error:{code:"no_org",message:"No active organisation"}},{status:400});const block=await tenantWriteEntitlementBlock(session);if(block)return writeEntitlementResponse(block);let state:string;try{state=createMetaOAuthState(session.organisationId)}catch(e){return NextResponse.json({error:{code:"meta_state",message:e instanceof Error?e.message:"Could not create OAuth state"}},{status:503})}const url=buildMetaInsightsAuthorizeUrl(state);if(!url.ok)return NextResponse.json({error:{code:"meta_config",message:url.message}},{status:503});return NextResponse.redirect(url.url)}
