import type { RoadmapItem } from "./index";

/**
 * Forward product horizon. Complements the shipped/current roadmap with the capabilities
 * DigitalGate needs to become a category-leading intelligent business operating platform.
 * Keep these explicit rather than hiding ambition in prose so progress remains measurable.
 */
export const PLATFORM_STRATEGIC_ROADMAP: RoadmapItem[] = [
  { id:"future.intelligence.graph", area:"Intelligence Layer", label:"Business Knowledge Graph", description:"Continuously relate customers, people, companies, assets, activity, documents, money, channels and outcomes into an explainable operating graph.", status:"in_progress", priority:"high", track:"gen2" },
  { id:"future.intelligence.memory", area:"Intelligence Layer", label:"Durable Business Memory", description:"Organisation-scoped facts, decisions, preferences, history and provenance with retention, correction and audit controls.", status:"in_progress", priority:"high", track:"gen2" },
  { id:"future.intelligence.aida", area:"Intelligence Layer", label:"Aida Business Copilot", description:"Cross-platform conversational operating layer that can understand, recommend and execute permissioned business actions with evidence.", status:"in_progress", priority:"high", track:"gen2" },
  { id:"future.intelligence.prediction", area:"Intelligence Layer", label:"Predictive Business Intelligence", description:"Forecast revenue, pipeline, churn, capacity, cash pressure, lead conversion and operational risk with confidence and explainability.", status:"planned", priority:"high", track:"gen2" },
  { id:"future.intelligence.autonomy", area:"Intelligence Layer", label:"Autonomous Operations", description:"Goal-based agents that monitor the business, propose actions, execute approved workflows and learn from measured outcomes.", status:"planned", priority:"high", track:"gen2" },
  { id:"future.intelligence.decision", area:"Intelligence Layer", label:"Decision & Scenario Engine", description:"What-if planning, scenario comparison, recommended actions and measurable post-decision learning.", status:"planned", priority:"high", track:"gen2" },
  { id:"future.platform.mobile", area:"Platform", label:"Native-quality mobile experience", description:"Responsive/PWA baseline through to mobile-first workflows, notifications, capture and field operation parity.", status:"in_progress", priority:"high", track:"gen2" },
  { id:"future.platform.search", area:"Platform", label:"Universal Search & Command Palette", description:"One search across people, companies, jobs, properties, bookings, documents, communications, knowledge and actions.", status:"planned", priority:"high", track:"gen2" },
  { id:"future.platform.notifications", area:"Platform", label:"Intelligent Notification Centre", description:"Prioritised alerts, digests, escalation rules and Aida summaries rather than noisy event feeds.", status:"planned", priority:"medium", track:"gen2" },
  { id:"future.platform.marketplace", area:"Platform", label:"App & Integration Marketplace", description:"Discover, purchase, provision and govern DigitalGate apps, partner apps, connectors and industry packs.", status:"planned", priority:"medium", track:"gen2" },
  { id:"future.platform.enterprise", area:"Platform", label:"Enterprise Governance", description:"Advanced RBAC, SSO/SCIM, policy controls, approvals, data retention, audit exports and delegated administration.", status:"planned", priority:"medium", track:"gen2" },
  { id:"future.crm.ai", area:"CRM", label:"AI Relationship Intelligence", description:"Relationship strength, next-best-action, duplicate resolution, lifecycle prediction, buying signals and automatic CRM hygiene.", status:"planned", priority:"high", appId:"crm", track:"gen2" },
  { id:"future.crm.sales", area:"CRM", label:"Sales Workspace", description:"Sequences, forecasting, pipeline coaching, meeting intelligence, proposals, tasks and conversion analytics in one workflow.", status:"planned", priority:"high", appId:"crm", track:"gen2" },
  { id:"future.commerce.accounting", area:"Commerce", label:"Financial Operations Hub", description:"Receivables, recurring billing, payment reconciliation, cash forecasting, margin intelligence and accounting connectors.", status:"planned", priority:"high", appId:"commerce", track:"gen2" },
  { id:"future.documents.ai", area:"Documents", label:"AI Document Workspace", description:"Generate, collaborate, approve, sign, extract structured data, ingest knowledge and automate document-driven workflows.", status:"planned", priority:"medium", appId:"documents", track:"gen2" },
  { id:"future.communications.omnichannel", area:"Communications", label:"Omnichannel Communications", description:"Email, SMS, voice, web chat and social messaging with unified identity, consent, history and automation.", status:"planned", priority:"high", appId:"communications", track:"gen2" },
  { id:"future.websites.optimisation", area:"Websites", label:"Autonomous Website Optimisation", description:"AI-assisted content, conversion testing, personalisation, technical health, accessibility and continuous SEO/AI visibility improvements.", status:"planned", priority:"high", appId:"websites", track:"gen2" },
  { id:"future.automation.agentic", area:"Automation", label:"Agentic Workflow Builder", description:"Natural-language and visual workflows with approvals, branches, retries, human handoff, reusable recipes and outcome analytics.", status:"planned", priority:"high", appId:"automation", track:"gen2" },
  { id:"future.analytics.semantic", area:"Analytics", label:"Business Semantic Layer", description:"Trusted metric definitions, cross-app attribution, natural-language analysis, anomaly detection and drill-through reporting.", status:"planned", priority:"high", appId:"analytics", track:"gen2" },
  { id:"future.growth.closedloop", area:"Growth Engine", label:"Closed-loop Growth Intelligence", description:"Connect discovery → audit → campaign → lead → sale → revenue so acquisition recommendations learn from real outcomes.", status:"planned", priority:"high", appId:"prospecting", track:"gen2" },
  { id:"future.re.full", area:"Real Estate", label:"Complete Agency Operating System", description:"Prospecting, appraisals, listings, buyers, inspections, offers, agreements, vendor reporting, settlements, portal syndication, trust/compliance integrations and AI agent workflows.", status:"in_progress", priority:"high", appId:"real-estate", track:"gen2" },
  { id:"future.pm.full", area:"Property Management", label:"Complete Property Management OS", description:"Owners, tenants, properties, leases, arrears, inspections, maintenance, compliance, communications, accounting integrations and portfolio intelligence.", status:"in_progress", priority:"high", appId:"property-management", track:"gen2" },
  { id:"future.commercial.full", area:"Commercial", label:"Complete Commercial Property OS", description:"Leasing, sales, tenancy schedules, deals, inspections, proposals, documents, property intelligence, campaigns and asset performance.", status:"in_progress", priority:"high", appId:"commercial", track:"gen2" },
  { id:"future.accommodation.full", area:"Accommodation", label:"Complete Accommodation OS", description:"Direct booking, availability, rates, guests, housekeeping, OTA sync, messaging, payments, reviews, revenue management and property performance.", status:"in_progress", priority:"high", appId:"accommodation", track:"gen2" },
  { id:"future.services.full", area:"Services", label:"Complete Field Services OS", description:"Leads, estimates, jobs, scheduling, dispatch, field capture, recurring work, timesheets, materials, invoicing, customer portal and AI scheduling/quoting.", status:"in_progress", priority:"high", appId:"services", track:"gen2" },
  { id:"future.finance.full", area:"Finance", label:"Complete Finance & Broking OS", description:"Lead-to-settlement workflow, applications, documents, lender/product integrations, compliance, communications, commissions, reviews and AI file preparation.", status:"in_progress", priority:"high", appId:"finance", track:"gen2" },
  { id:"future.automotive.full", area:"Automotive", label:"Complete Automotive OS", description:"Inventory, enquiries, test drives, valuation/trade-in, finance, deals, delivery, service follow-up, marketing and customer lifecycle intelligence.", status:"planned", priority:"medium", appId:"automotive", track:"gen2" },
  { id:"future.creator.full", area:"Creator", label:"Complete Creator OS", description:"Audience CRM, content planning, publishing, campaigns, partnerships, digital products, memberships, revenue analytics and rights/assets.", status:"planned", priority:"medium", appId:"creator", track:"gen2" },
  { id:"future.reputation.ai", area:"Reputation", label:"AI Reputation Management", description:"Review monitoring, request automation, response assistance, theme/sentiment intelligence, recovery workflows and reputation opportunity scoring.", status:"in_progress", priority:"medium", appId:"reviews", track:"gen2" },
  { id:"future.social.publisher", area:"Social Management", label:"Full Social Publishing & Intelligence", description:"OAuth publishing, calendar, approvals, inbox, engagement, listening, content intelligence and measurable lead/revenue attribution.", status:"planned", priority:"medium", appId:"social", track:"gen2" },
  { id:"future.ai.visibility", area:"SEO & Visibility", label:"Live AI Visibility Monitoring", description:"Observe brand/entity presence across AI answer engines, citations and prompts with competitors, trends, evidence and recommended actions.", status:"planned", priority:"high", appId:"ai-visibility", track:"gen2" },
  { id:"future.seo.autonomous", area:"SEO & Visibility", label:"Autonomous SEO Engine", description:"Search Console/Analytics-backed keyword, technical, content, local and entity optimisation with measured impact and guarded execution.", status:"planned", priority:"high", appId:"seo", track:"gen2" },
  { id:"future.infrastructure.managed", area:"Infrastructure", label:"Managed Digital Infrastructure", description:"Domains, DNS, SSL, hosting, deployments, uptime, performance, email/domain health, backups and incident intelligence from one control plane.", status:"in_progress", priority:"high", appId:"infrastructure", track:"gen2" },
];
