/**
 * DigitalGate public Apps catalog — marketing site only.
 * Depth: full (sell/demo now) · lite (architecture, honest status) · soon (hub + template).
 */

export const LAYERS = [
  {
    id: "core",
    name: "Core",
    verb: "run",
    tagline: "every business",
    intro:
      "The operating foundation. Contacts, work, revenue and communications live here so every other App has something real to act on.",
  },
  {
    id: "infrastructure",
    name: "Infrastructure",
    verb: "power",
    tagline: "operate digitally",
    intro:
      "How your business exists online — website, domains, email and hosting — connected to the same platform, not a separate IT stack.",
  },
  {
    id: "industry",
    name: "Industry",
    verb: "specialise",
    tagline: "vertical workflows",
    intro:
      "The same Core, specialised for how your industry actually works. Real Estate is the flagship. Other verticals ship with honest status.",
  },
  {
    id: "growth",
    name: "Growth",
    verb: "grow",
    tagline: "visibility, acquisition, conversion",
    intro:
      "Find demand, understand what to do next, and act. Growth Apps sit on Core — they are not a second CRM.",
  },
];

const LOOP = [
  "Connect",
  "Centralise",
  "Understand",
  "Decide",
  "Act",
  "Learn",
  "Grow",
];

function app(partial) {
  const layerName =
    partial.layer === "core"
      ? "Core"
      : partial.layer === "infrastructure"
        ? "Infrastructure"
        : partial.layer === "industry"
          ? "Industry"
          : "Growth";
  const defaults = [
    `DigitalGate ${partial.name}`,
    partial.name,
    `${layerName} App`,
    "DigitalGate Apps",
    "business operating platform",
    "Australia",
  ];
  return {
    loop: LOOP,
    highlight: ["Centralise"],
    related: [],
    flow: [],
    objects: [],
    notThis: "",
    commercial:
      "DigitalGate is sold as Platform → Apps → Services → Success. Apps are not included in the platform subscription unless explicitly stated.",
    ...partial,
    keywords: [...new Set([...defaults, ...(partial.keywords || [])])],
  };
}

export const APPS = [
  // ——— Core · full ———
  app({
    slug: "crm",
    layer: "core",
    name: "CRM",
    depth: "full",
    badge: "Included",
    status: "Available on the platform foundation (Starter, Growth and Scale).",
    headline: "One customer record for the whole operating system.",
    subhead:
      "Not another CRM to replace Salesforce. CRM is how people, companies and conversations enter DigitalGate — then feed Opportunities, Industry Apps and Growth.",
    what: "A shared customer system of record: people, companies, notes and history that every App can use.",
    connects:
      "Industry pipelines, Opportunities, Tasks, Communications, Commerce and Growth all read the same Contact — they do not keep a private copy.",
    who: "Any business running customers on DigitalGate — especially Founding Real Estate and Accommodation operators who need one record, not five tools.",
    highlight: ["Connect", "Centralise"],
    flow: [
      "Lead",
      "Contact",
      "Company",
      "Activity",
      "Opportunity",
      "Industry workflow",
      "Revenue",
    ],
    objects: [
      "Contact",
      "Company",
      "Activity",
      "Opportunity",
      "Task",
      "Communication",
    ],
    notThis:
      "This is not “CRM — here’s another CRM.” If the record stops at a contact list, DigitalGate has failed. The point is that every object feeds the wider platform.",
    related: ["contacts", "opportunities", "communications", "real-estate"],
    included: true,
  }),
  app({
    slug: "opportunities",
    layer: "core",
    name: "Opportunities",
    depth: "full",
    badge: "Included",
    status: "Available on the platform foundation.",
    headline: "See the work that should happen next — not just a deal board.",
    subhead:
      "Opportunities are how DigitalGate turns activity into a ranked pipeline. Industry Apps specialise the stages; Core keeps the commercial object.",
    what: "Pipeline opportunities with stage, value and next action — the same object Real Estate listings, Accommodation stays and services jobs hang off.",
    connects:
      "Created from Contacts and Industry Apps; scored and ranked with the Opportunity Engine; executed through Tasks and Automation.",
    who: "Founding operators who need to see revenue work in one place — not a spreadsheet beside the CRM.",
    highlight: ["Understand", "Decide"],
    flow: [
      "Signal",
      "Contact",
      "Opportunity",
      "Next action",
      "Task or Automation",
      "Outcome",
      "Learn",
    ],
    objects: ["Opportunity", "Contact", "Task", "Activity"],
    notThis:
      "Not a Kanban toy. Stages exist so the platform can understand, decide and act — then learn whether the action worked.",
    related: ["crm", "prospecting", "automation", "real-estate"],
    included: true,
  }),

  // ——— Core · lite ———
  app({
    slug: "contacts",
    layer: "core",
    name: "Contacts",
    depth: "lite",
    badge: "Included",
    status: "Available — universal person record across Apps.",
    headline: "One person. Every App.",
    subhead:
      "Guests, vendors, buyers, clients and leads are the same Contact with a role — not duplicate databases.",
    what: "The universal person record. Industry Apps add context (guest, vendor, buyer) without cloning the human.",
    connects: "CRM, Real Estate, Accommodation, Communications and Commerce all resolve to Contact.",
    who: "Every DigitalGate organisation.",
    highlight: ["Centralise"],
    related: ["crm", "opportunities"],
    included: true,
  }),
  app({
    slug: "tasks",
    layer: "core",
    name: "Tasks",
    depth: "lite",
    badge: "Included",
    status: "Available — follow-ups on contacts and opportunities.",
    headline: "Decide, then do.",
    subhead:
      "Tasks are how recommendations become work. They sit on Contacts and Opportunities — not a separate to-do app.",
    what: "Create, complete and list follow-ups in the operating loop: Decide → Act.",
    connects: "Opportunities, CRM, Automation and Command Centre recommended actions.",
    who: "Teams who need the next action attached to the record, not lost in email.",
    highlight: ["Decide", "Act"],
    related: ["opportunities", "calendar", "automation"],
    included: true,
  }),
  app({
    slug: "calendar",
    layer: "core",
    name: "Calendar",
    depth: "lite",
    badge: "Included",
    status: "Available — bookings and schedule on Core; Industry Apps specialise the diary.",
    headline: "Time belongs on the same platform as the customer.",
    subhead:
      "Appraisals, stays and follow-ups should not live in a personal calendar the platform cannot see.",
    what: "Schedule and bookings connected to Contacts, Opportunities and Industry workflows.",
    connects: "Real Estate appraisals, Accommodation stays, Tasks and Communications.",
    who: "Operators whose day is appointments, not just a pipeline board.",
    highlight: ["Act"],
    related: ["tasks", "real-estate", "accommodation"],
    included: true,
  }),
  app({
    slug: "documents",
    layer: "core",
    name: "Documents",
    depth: "lite",
    badge: "Included",
    status: "Available as files on business records — deeper DMS continues.",
    headline: "Files attached to the work, not a drive beside it.",
    subhead: "Contracts, briefs and assets should sit on the Contact, Opportunity or listing they belong to.",
    what: "Documents linked to Core and Industry records so the operating system has the file, not just a mention of it.",
    connects: "CRM, Opportunities, Real Estate and Accommodation records.",
    who: "Teams tired of searching Slack and email for the latest PDF.",
    highlight: ["Centralise"],
    related: ["crm", "opportunities"],
    included: true,
  }),
  app({
    slug: "communications",
    layer: "core",
    name: "Communications",
    depth: "lite",
    badge: "Included",
    status: "Available — email and message history in context. Voice remains Early Access.",
    headline: "The conversation stays on the record.",
    subhead:
      "If the email lives only in someone’s inbox, the platform cannot Understand or Learn.",
    what: "Email and message history attached to Contacts and Opportunities.",
    connects: "CRM, Automation, AI Communications (Early Access) and Industry follow-up.",
    who: "Operators who need a shared history, not a personal mailbox as the system of record.",
    highlight: ["Connect", "Act"],
    related: ["crm", "ai-communications", "automation"],
    included: true,
  }),
  app({
    slug: "commerce",
    layer: "core",
    name: "Commerce",
    depth: "lite",
    badge: "Early Access",
    status: "Early Access — quotes, invoices and payments rolling out. Not a finished billing suite.",
    headline: "Revenue objects on the same foundation.",
    subhead:
      "Quotes and invoices should close the loop from Opportunity to cash — without a second finance product.",
    what: "Quotes, invoices, products and subscriptions as Core commercial objects.",
    connects: "Opportunities, Contacts, Accommodation payments and platform billing (separate).",
    who: "Founding operators who need to quote and invoice without leaving DigitalGate.",
    highlight: ["Act", "Grow"],
    related: ["opportunities", "crm"],
    included: true,
  }),

  // ——— Infrastructure ———
  app({
    slug: "website",
    layer: "infrastructure",
    name: "Website Connection & Management",
    depth: "lite",
    badge: "Available",
    status: "Available — connect and manage your site with platform context. Depth expands with plan.",
    headline: "Your website is a platform surface — not a brochure on the side.",
    subhead:
      "When the site is connected, CRM, SEO, AI Visibility and Prospecting can see the same presence.",
    what: "Connect, health-check and manage the website that already represents your business.",
    connects: "SEO, AI Visibility, Reputation, Prospecting audits and Industry enquiry capture.",
    who: "Businesses whose site should feed the operating system, not sit in a separate agency login.",
    highlight: ["Connect"],
    related: ["website-builder", "seo", "ai-visibility"],
  }),
  app({
    slug: "website-builder",
    layer: "infrastructure",
    name: "Website Builder",
    depth: "lite",
    badge: "Growth+",
    status: "Growth+ — advanced creation and publishing. Not included in every platform plan.",
    headline: "Build and publish inside the same operating system.",
    subhead:
      "Pages, brand and funnels that can talk to Contacts and Industry Apps — not a standalone CMS clone.",
    what: "Create, edit and publish sites from DigitalGate, with honest progressive capability by plan.",
    connects: "Website Connection, Domains, DNS, SEO and capture funnels.",
    who: "Growth and Scale operators who want the site on the platform, not WordPress plus a CRM.",
    highlight: ["Connect", "Act"],
    related: ["website", "domains", "seo"],
  }),
  app({
    slug: "domains",
    layer: "infrastructure",
    name: "Domains",
    depth: "lite",
    badge: "Early Access",
    status: "Early Access — connect and manage domains from the platform.",
    headline: "Digital identity on the operating system.",
    what: "Search, connect and point domains without treating DNS as a separate vendor relationship.",
    connects: "Website Connection, DNS, Email and Make-it-live checklists.",
    who: "Operators bringing a live domain onto DigitalGate.",
    highlight: ["Connect"],
    related: ["dns", "website", "email"],
  }),
  app({
    slug: "dns",
    layer: "infrastructure",
    name: "DNS",
    depth: "lite",
    badge: "Early Access",
    status: "Early Access — inspect and apply website DNS when the zone is writable.",
    headline: "Records beside the site they serve.",
    what: "DNS console alongside domains and hosting — not a mystery at the registrar.",
    connects: "Domains, Website Connection, Email and SSL (when ready).",
    who: "Teams going live on DigitalGate Infrastructure.",
    highlight: ["Connect"],
    related: ["domains", "website", "email"],
  }),
  app({
    slug: "email",
    layer: "infrastructure",
    name: "Email",
    depth: "lite",
    badge: "Early Access",
    status: "Early Access — mailbox and transactional email infrastructure, rolling out honestly.",
    headline: "Mail that the platform can see.",
    what: "Infrastructure for sending and receiving in context of the business — not a consumer inbox product.",
    connects: "Communications, Domains, DNS and Automation.",
    who: "Organisations ready to stop treating email as a silo.",
    highlight: ["Connect", "Act"],
    related: ["communications", "domains", "automation"],
  }),
  app({
    slug: "hosting",
    layer: "infrastructure",
    name: "Hosting",
    depth: "soon",
    badge: "Coming Soon",
    status: "Coming Soon — hosting abstraction as it becomes commercially ready. Not sold as a standalone host today.",
    headline: "Presence without a separate hosting company.",
    what: "Managed hosting for DigitalGate sites when the product is ready to sell — not a promise of cPanel.",
    connects: "Website Builder, Domains, SSL, Backups and Cloudflare.",
    who: "Future operators who want site + OS from one vendor.",
    related: ["website-builder", "ssl", "backups"],
  }),
  app({
    slug: "ssl",
    layer: "infrastructure",
    name: "SSL",
    depth: "soon",
    badge: "Coming Soon",
    status: "Coming Soon — certificates managed with your site.",
    headline: "Trust, attached to the domain.",
    what: "SSL as Infrastructure, not a checkbox you chase at the registrar.",
    connects: "Domains, Hosting and Website Connection.",
    who: "Sites going live on DigitalGate when this ships.",
    related: ["domains", "hosting"],
  }),
  app({
    slug: "backups",
    layer: "infrastructure",
    name: "Backups",
    depth: "soon",
    badge: "Coming Soon",
    status: "Coming Soon — backup and restore for managed presence.",
    headline: "Recover the site the platform actually runs.",
    what: "Backups for DigitalGate-managed presence — not a generic backup SKU yet.",
    connects: "Hosting, Website Builder and Website Connection.",
    who: "Operators on managed Infrastructure once commercially ready.",
    related: ["hosting", "website-builder"],
  }),
  app({
    slug: "cloudflare",
    layer: "infrastructure",
    name: "Cloudflare",
    depth: "soon",
    badge: "Coming Soon",
    status: "Coming Soon — CDN and edge controls when ready.",
    headline: "Edge, without a second control panel story.",
    what: "Cloudflare as an Infrastructure capability when DigitalGate can operate it honestly.",
    connects: "Hosting, DNS, SSL and Website Connection.",
    who: "Sites that need edge performance as part of the OS.",
    related: ["hosting", "dns"],
  }),

  // ——— Industry · full ———
  app({
    slug: "real-estate",
    layer: "industry",
    name: "Real Estate",
    depth: "full",
    badge: "Founding",
    commercialStatus: "FOUNDING 10 · AVAILABLE NOW",
    status:
      "Flagship Industry App. Currently operating in production on Roe Realty and available to selected Founding Customers.",
    headline: "Turn your property pipeline into an operating system.",
    subhead:
      "Vendor work, buyer work, appraisals and listings are not a CRM template. They are a specialised loop on DigitalGate Core.",
    what: "The vertical operating workflow for sales agencies: vendors, buyers, appraisals, listings and settlements — on the same Contacts and Opportunities every other App uses.",
    connects:
      "Every listing, lead and appraisal writes Core objects. Growth Apps (AI Visibility, SEO, Prospecting) and Automation then see the same pipeline.",
    who: "Australian sales agencies in the Founding Customer Programme — starting with operators who already run on DigitalGate (including Roe Realty).",
    highlight: ["Connect", "Centralise", "Understand", "Decide", "Act", "Grow"],
    flow: [
      "Lead",
      "Contact",
      "Opportunity",
      "Appraisal",
      "Listing",
      "Buyer activity",
      "Deal",
      "Revenue",
    ],
    objects: [
      "Vendor lead",
      "Buyer lead",
      "Property / appraisal",
      "Listing",
      "Contact",
      "Opportunity",
      "Task",
    ],
    notThis:
      "Not “Vendor CRM, Buyer CRM, Appraisals, Listings” as four products. Those are stages of one operating system. If a listing does not feed Contacts, Opportunities and Growth, it is just another agency tool.",
    whatYouGet: [
      "Vendor Lead Pipeline",
      "Buyer Lead Pipeline",
      "Appraisal Management",
      "Listing Management",
      "Buyer Activity",
      "Tasks & Follow-up",
      "Opportunity Management",
      "Settlement / Deal Tracking",
      "Connected CRM records",
      "Automation across the workflow",
      "AI and Growth Apps operating against the same data",
    ],
    builtFor: [
      "Boutique real estate agencies",
      "Independent agencies",
      "Sales teams",
      "Property-focused businesses",
      "Agencies wanting to replace fragmented CRM, spreadsheets and disconnected workflows",
    ],
    builtForNote: "Designed for Australian real estate operations.",
    productionProof: {
      intro:
        "The Real Estate App is already operating on DigitalGate through Roe Realty, providing the production reference for the Founding Customer programme.",
      reference: {
        name: "Roe Realty",
        label: "Real Estate · Production Reference",
      },
      items: [
        { name: "Vendor Pipeline", status: "Live" },
        { name: "Property & Appraisal Workflow", status: "Live" },
        { name: "Buyer Management", status: "Live / developing" },
      ],
    },
    pricing:
      "Industry App add-on from $99/mo · Platform subscription required. Founding Customer terms on Pricing.",
    keywords: [
      "real estate CRM",
      "property pipeline",
      "vendor leads",
      "buyer CRM",
      "appraisal software",
    ],
    related: ["crm", "opportunities", "prospecting", "ai-visibility"],
  }),
  app({
    slug: "accommodation",
    layer: "industry",
    name: "Accommodation",
    depth: "full",
    badge: "Early Access",
    status: "Early Access — bookings, units, calendar and housekeeping in use with founding properties.",
    headline: "Direct stays on the same operating system as the rest of the business.",
    subhead:
      "Guests, units, availability and turnover are Industry workflow — not a channel manager pretending to be a PMS.",
    what: "Units, availability, stay bookings, guests, housekeeping and payments — specialised for short-stay without a second guest database.",
    connects:
      "Guests are Contacts. Stays create operational work. Reviews and Growth Apps see the same property. Website and calendar connect to Core.",
    who: "Founding accommodation operators (including Currumbin Valley Hideaway) who want direct bookings and operations on DigitalGate.",
    highlight: ["Connect", "Centralise", "Act", "Learn", "Grow"],
    flow: [
      "Enquiry",
      "Guest (Contact)",
      "Stay",
      "Calendar",
      "Housekeeping",
      "Review",
      "Direct booking",
      "Revenue",
    ],
    objects: ["Unit", "Stay booking", "Guest Contact", "Calendar block", "Payment"],
    notThis:
      "Not another Lodgify. Channel sync exists to serve the operating system. The guest still has to become a Contact the rest of DigitalGate can Understand and Act on.",
    related: ["crm", "calendar", "reputation", "website"],
  }),

  // ——— Industry · soon ———
  app({
    slug: "property-management",
    layer: "industry",
    name: "Property Management",
    depth: "soon",
    badge: "Coming Soon",
    status: "Coming Soon — long-term rentals (owners, tenants, leases). Not Real Estate sales.",
    headline: "Rent rolls on the same Core as sales — when the App is ready.",
    what: "Owners, tenants, leases, maintenance and arrears as a specialised Industry App — architecture reserved, not sold as ready.",
    connects: "Will share Contacts, Documents, Tasks and Commerce with Core. Distinct from Real Estate sales.",
    who: "Agencies and PMs who want one platform later — register interest, do not expect a live PM product today.",
    related: ["real-estate", "commercial-property"],
  }),
  app({
    slug: "commercial-property",
    layer: "industry",
    name: "Commercial Property",
    depth: "soon",
    badge: "Coming Soon",
    status: "Coming Soon — commercial sales and leasing. In development, not Founding-ready.",
    headline: "Commercial workflows without a second stack.",
    what: "Commercial assets, leasing and landlord/tenant records on DigitalGate Core when built.",
    connects: "Same Contacts and Opportunities model as Real Estate — different operating objects.",
    who: "Commercial operators planning ahead with Founding interest.",
    related: ["real-estate", "property-management"],
  }),
  app({
    slug: "property-development",
    layer: "industry",
    name: "Property Development",
    depth: "soon",
    badge: "Later",
    status: "Later — architecture reserved. Not in the current build.",
    headline: "Projects, lots and stages — later.",
    what: "Development projects on the property ecosystem. Explicitly not being built for Founding 10.",
    connects: "Will sit on the same property Core as sales and PM when the time comes.",
    who: "Developers who want the ecosystem mapped — not a product to buy today.",
    related: ["real-estate", "commercial-property"],
  }),
  app({
    slug: "services",
    layer: "industry",
    name: "Services",
    depth: "soon",
    badge: "Coming Soon",
    status: "Coming Soon — jobs, quotes and scheduling. One App with Service Templates, not per-trade products.",
    headline: "Trades and services on Core — when commercially ready.",
    what: "Jobs, scheduling and quotes for service businesses. Quotes already lean on Commerce.",
    connects: "Contacts, Tasks, Calendar, Commerce. Templates specialise the job — we will not ship 40 trade Apps.",
    who: "Service operators in the wider Founding mix — not the primary Real Estate wedge.",
    related: ["crm", "commerce", "calendar"],
  }),
  app({
    slug: "finance",
    layer: "industry",
    name: "Finance",
    depth: "soon",
    badge: "Coming Soon",
    status: "Coming Soon — broker and lending workflows in development.",
    headline: "Finance pipelines on the same Contacts.",
    what: "Broker / lending operating workflow when ready — not a live product for Founding 10 sales.",
    connects: "Contacts, Opportunities, Documents and Communications.",
    who: "Brokers who want to register interest, not onboard a finished App.",
    related: ["crm", "opportunities", "prospecting"],
  }),
  app({
    slug: "automotive",
    layer: "industry",
    name: "Automotive",
    depth: "soon",
    badge: "Coming Soon",
    status: "Coming Soon — dealership inventory and sales. In development.",
    headline: "Stock and sales without a dealer-only island.",
    what: "Inventory, leads and test drives as an Industry App when commercially ready.",
    connects: "Contacts, Opportunities, Calendar and Communications.",
    who: "Dealers planning on DigitalGate later.",
    related: ["crm", "opportunities"],
  }),
  app({
    slug: "creator",
    layer: "industry",
    name: "Creator",
    depth: "soon",
    badge: "Coming / Founding",
    status: "Coming / Founding interest — audience and creator studio. Not commercially ready.",
    headline: "Audience businesses on the same OS.",
    what: "Memberships and creator workflows as a future Industry App. Founding interest is welcome; do not sell it as live.",
    connects: "Contacts, Commerce, Website and Communications when it ships.",
    who: "Creators in the DigitalGate network who want a seat on the roadmap.",
    related: ["commerce", "website", "ai-communications"],
  }),

  // ——— Growth · full ———
  app({
    slug: "ai-visibility",
    layer: "growth",
    name: "AI Visibility",
    depth: "full",
    badge: "Available",
    status: "Available as a Growth App add-on. Scores use observable website signals — not invented ChatGPT rankings.",
    headline: "Be findable where buyers now ask questions.",
    subhead:
      "AI Visibility is not a consultancy SKU. It is how DigitalGate Understands whether your presence is structured for search and AI systems — then tells you what to Act on.",
    what: "Readiness for Google and AI search from live presence signals (schema, entity, technical) shared with SEO.",
    connects:
      "Website Connection, SEO Engine, Prospecting audits and the Digital Twin. Findings become Opportunities and Tasks — not a PDF that dies in email.",
    who: "Founding operators who already have a site on or connected to DigitalGate and need a honest visibility story.",
    highlight: ["Understand", "Decide", "Grow"],
    flow: [
      "Website connected",
      "Presence signals",
      "AI Visibility score",
      "Gaps",
      "Recommended action",
      "Task or content change",
      "Re-measure",
    ],
    objects: ["Website", "Presence audit", "Opportunity", "Task"],
    notThis:
      "Not “we will get you cited by ChatGPT.” We measure what we can observe. That honesty is the product.",
    related: ["seo", "prospecting", "website", "automation"],
  }),
  app({
    slug: "seo",
    layer: "growth",
    name: "SEO",
    depth: "full",
    badge: "Available",
    status: "Available as a Growth App add-on. Same presence audit as AI Visibility — different job.",
    headline: "Technical and content truth, on the platform that owns the site.",
    subhead:
      "SEO here is not an agency retainer. It is how DigitalGate Understands the site you already run, then feeds Decide → Act.",
    what: "Audits, technical signals and optimisation guidance from the live site — one source of truth with AI Visibility.",
    connects:
      "Website Connection / Builder, AI Visibility, Prospecting, Real Estate landing pages and Automation follow-through.",
    who: "Founding businesses whose growth depends on being found — especially local services and Real Estate.",
    highlight: ["Understand", "Act", "Learn"],
    flow: [
      "Site connected",
      "Audit",
      "Issues",
      "Fix or task",
      "Publish",
      "Re-audit",
      "Learn",
    ],
    objects: ["Website", "SEO audit", "Task", "Page"],
    notThis:
      "Not a ranking guarantee and not a separate SEO company. If the audit cannot become a Task on a Contact or Opportunity, it is theatre.",
    related: ["ai-visibility", "website", "prospecting", "real-estate"],
  }),
  app({
    slug: "automation",
    layer: "growth",
    name: "Automation",
    depth: "full",
    badge: "Available",
    status: "Available — workflows across Core and Apps. Listed here as the commercial Act surface.",
    headline: "When the platform knows what to do, it should do it.",
    subhead:
      "Automation is how DigitalGate Acts. It is not a Zapier clone in the Apps aisle. Rules fire on Core events — leads, opportunities, payments, stays — so people are not the integration layer.",
    what: "Triggers, multi-step workflows and logs that move work from Decide to Act: create tasks, send communications, advance opportunities.",
    connects:
      "CRM, Opportunities, Real Estate, Accommodation, Commerce, Communications and Growth signals. The Event Bus is platform; this App is how operators shape it.",
    who: "Founding operators who have real records and need the next step to happen without another spreadsheet.",
    highlight: ["Decide", "Act", "Learn"],
    flow: [
      "Event",
      "Rule",
      "Action",
      "Task / message / stage",
      "Outcome",
      "Log",
      "Improve the rule",
    ],
    objects: ["Automation rule", "Event", "Task", "Communication", "Opportunity"],
    notThis:
      "Not “buy Automation because other CRMs have it.” If a workflow does not change a Core object, it is decoration.",
    related: ["opportunities", "prospecting", "communications", "crm"],
  }),
  app({
    slug: "prospecting",
    layer: "growth",
    name: "Prospecting & Opportunity Engine",
    depth: "full",
    badge: "Early Access",
    status: "Early Access — Business Discovery plus ranked next actions. One of the strongest commercial Growth products.",
    headline: "Find the opportunities your business should act on next.",
    subhead:
      "This is the Understand → Decide → Act product. Discovery finds businesses. Presence and platform signals score them. The Opportunity Engine ranks what to do. Automation can act. That is not a CRM feature list — it is the DigitalGate thesis.",
    what: "Prospect discovery (Places + ABN when configured), digital presence signals, scoring, recommended actions and a path into CRM / outreach — staff-operated today, productised as a Growth App.",
    connects:
      "Combines prospect discovery, website and Google signals, AI Visibility, CRM history, lead and opportunity scoring, recommended actions and automated outreach as those pieces are ready. Imports land as Growth prospects — not a silent CRM dump.",
    who: "DigitalGate and Founding operators who need a pipeline of who to speak to next — starting with agency and local-service prospecting on the Gold Coast and beyond.",
    highlight: ["Understand", "Decide", "Act", "Learn", "Grow"],
    flow: [
      "Discover",
      "Select",
      "Import prospect",
      "Presence audit",
      "Score",
      "Recommend",
      "Act",
      "Learn",
    ],
    objects: [
      "Discovery candidate",
      "Growth prospect",
      "Presence audit",
      "Opportunity",
      "Recommended action",
      "Task",
    ],
    notThis:
      "Not “we have a CRM, so we prospect.” CRM stores the relationship. This App decides who deserves attention — then the rest of DigitalGate can Act and Learn.",
    keywords: [
      "opportunity engine",
      "prospect discovery",
      "ABN lookup",
      "lead scoring",
      "business intelligence",
    ],
    related: ["opportunities", "ai-visibility", "seo", "automation", "crm"],
  }),

  // ——— Growth · lite ———
  app({
    slug: "analytics",
    layer: "growth",
    name: "Analytics",
    depth: "lite",
    badge: "Early Access",
    status: "Early Access — KPI snapshots and connectors. Honest empty states when data is missing.",
    headline: "Measure so the loop can Learn.",
    what: "Reporting and connectors so DigitalGate can see performance — not a vanity dashboard.",
    connects: "Website, Commerce, Industry Apps and Opportunity outcomes.",
    who: "Operators who want Learn → Grow without exporting to another BI tool first.",
    highlight: ["Learn", "Grow"],
    related: ["seo", "opportunities", "commerce"],
  }),
  app({
    slug: "social",
    layer: "growth",
    name: "Social",
    depth: "lite",
    badge: "Early Access",
    status: "Early Access — publish and manage social from the platform. Depth continues.",
    headline: "Distribution attached to the same customers.",
    what: "Social publishing as a Growth capability — not a Hootsuite replacement claim.",
    connects: "Contacts, Marketing, Reputation and Website.",
    who: "Teams who want social on the OS, knowing it is still early.",
    highlight: ["Act", "Grow"],
    related: ["reputation", "ai-communications", "website"],
  }),
  app({
    slug: "reputation",
    layer: "growth",
    name: "Reputation",
    depth: "lite",
    badge: "Early Access",
    status: "Early Access — review inbox and requests. Score only when real data exists.",
    headline: "What customers say, on the record.",
    what: "Reviews and reputation as a Growth App on Core review plumbing — no invented scores.",
    connects: "Accommodation stays, Real Estate settlements, Contacts and AI Visibility context.",
    who: "Operators who already collect reviews and want them inside DigitalGate.",
    highlight: ["Learn", "Grow"],
    related: ["accommodation", "ai-communications", "analytics"],
  }),
  app({
    slug: "ai-communications",
    layer: "growth",
    name: "AI Communications",
    depth: "lite",
    badge: "Early Access",
    status: "Early Access — AI-assisted communications. Voice Agents still in development — not a live call-centre product.",
    headline: "Assist the conversation. Do not fake a voice agent.",
    what: "AI-assisted messaging on Core Communications. Voice remains in development.",
    connects: "Communications, Contacts, Automation and Knowledge.",
    who: "Founding teams who want assistance now and voice later — without overclaiming.",
    highlight: ["Act"],
    related: ["communications", "automation", "crm"],
  }),
];

export function hrefFor(app) {
  return `/apps/${app.layer}/${app.slug}/`;
}

export function appBySlug(slug) {
  return APPS.find((a) => a.slug === slug);
}

export function appsInLayer(layerId) {
  return APPS.filter((a) => a.layer === layerId);
}
