/**
 * DigitalGate public Apps catalog — marketing site only.
 * Depth: full (sell/demo now) · lite (architecture, honest status) · soon (hub + template).
 */

export const LAYERS = [
  {
    id: "core",
    name: "Core",
    verb: "run",
    tagline: "every business",
    intro:
      "The operating foundation. Contacts, work, revenue and communications live here so every other App has something real to act on.",
  },
  {
    id: "infrastructure",
    name: "Infrastructure",
    verb: "power",
    tagline: "operate digitally",
    intro:
      "How your business exists online — website, domains, email and hosting — connected to the same platform, not a separate IT stack.",
  },
  {
    id: "industry",
    name: "Industry",
    verb: "specialise",
    tagline: "vertical workflows",
    intro:
      "Industry Apps are commercial verticals (+$99/mo). Templates specialise each vertical (1 included, +$29/mo each extra). Property and Services are Available; Hospitality & Accommodation, Finance and Creator & Media are Early Access. New business types become Templates — never new top-level Apps.",
  },
  {
    id: "growth",
    name: "Growth",
    verb: "grow",
    tagline: "visibility, acquisition, conversion",
    intro:
      "Optional Growth Apps, billed separately: Prospecting & Opportunity Engine $99 · AI Visibility $99 · SEO $99 · Automation $49 · Analytics $49 · Social $79 · Reputation Free. Advanced AI Communications / AI Voice Agents $99 is a Core Communications add-on (not a Growth App).",
  },
];

const LOOP = [
  "Connect",
  "Centralise",
  "Understand",
  "Decide",
  "Act",
  "Learn",
  "Grow",
];

function app(partial) {
  const layerName =
    partial.layer === "core"
      ? "Core"
      : partial.layer === "infrastructure"
        ? "Infrastructure"
        : partial.layer === "industry"
          ? "Industry"
          : "Growth";
  const defaults = [
    `DigitalGate ${partial.name}`,
    partial.name,
    `${layerName} App`,
    "DigitalGate Apps",
    "business operating platform",
    "Australia",
  ];
  return {
    loop: LOOP,
    highlight: ["Centralise"],
    related: [],
    flow: [],
    objects: [],
    notThis: "",
    commercial:
      "DigitalGate is sold as Platform → Apps → Services → Success. Apps are not included in the platform subscription unless explicitly stated.",
    ...partial,
    keywords: [...new Set([...defaults, ...(partial.keywords || [])])],
  };
}

export const APPS = [
  // ——— Core · full ———
  app({
    slug: "crm",
    layer: "core",
    name: "CRM",
    depth: "full",
    badge: "Included",
    status: "Available on the platform foundation (Starter, Growth and Scale).",
    headline: "One customer record for the whole operating system.",
    subhead:
      "Not another CRM to replace Salesforce. CRM is how people, companies and conversations enter DigitalGate — then feed Opportunities, Industry Apps and Growth.",
    what: "A shared customer system of record: people, companies, notes and history that every App can use.",
    connects:
      "Industry pipelines, Opportunities, Tasks, Communications, Commerce and Growth all read the same Contact — they do not keep a private copy.",
    who: "Any business running customers on DigitalGate — especially Founding Real Estate and Accommodation operators who need one record, not five tools.",
    highlight: ["Connect", "Centralise"],
    flow: [
      "Lead",
      "Contact",
      "Company",
      "Activity",
      "Opportunity",
      "Industry workflow",
      "Revenue",
    ],
    objects: [
      "Contact",
      "Company",
      "Activity",
      "Opportunity",
      "Task",
      "Communication",
    ],
    notThis:
      "This is not “CRM — here’s another CRM.” If the record stops at a contact list, DigitalGate has failed. The point is that every object feeds the wider platform.",
    related: ["contacts", "opportunities", "communications", "real-estate"],
    included: true,
  }),
  app({
    slug: "opportunities",
    layer: "core",
    name: "Opportunities",
    depth: "full",
    badge: "Included",
    status: "Available on the platform foundation.",
    headline: "See the work that should happen next — not just a deal board.",
    subhead:
      "Opportunities are how DigitalGate turns activity into a ranked pipeline. Industry Apps specialise the stages; Core keeps the commercial object.",
    what: "Pipeline opportunities with stage, value and next action — the same object Real Estate listings, Accommodation stays and services jobs hang off.",
    connects:
      "Created from Contacts and Industry Apps; scored and ranked with the Opportunity Engine; executed through Tasks and Automation.",
    who: "Founding operators who need to see revenue work in one place — not a spreadsheet beside the CRM.",
    highlight: ["Understand", "Decide"],
    flow: [
      "Signal",
      "Contact",
      "Opportunity",
      "Next action",
      "Task or Automation",
      "Outcome",
      "Learn",
    ],
    objects: ["Opportunity", "Contact", "Task", "Activity"],
    notThis:
      "Not a Kanban toy. Stages exist so the platform can understand, decide and act — then learn whether the action worked.",
    related: ["crm", "prospecting", "automation", "real-estate"],
    included: true,
  }),

  // ——— Core · lite ———
  app({
    slug: "contacts",
    layer: "core",
    name: "Contacts",
    depth: "lite",
    badge: "Included",
    status: "Available — universal person record across Apps.",
    headline: "One person. Every App.",
    subhead:
      "Guests, vendors, buyers, clients and leads are the same Contact with a role — not duplicate databases.",
    what: "The universal person record. Industry Apps add context (guest, vendor, buyer) without cloning the human.",
    connects: "CRM, Real Estate, Accommodation, Communications and Commerce all resolve to Contact.",
    who: "Every DigitalGate organisation.",
    highlight: ["Centralise"],
    related: ["crm", "opportunities"],
    included: true,
  }),
  app({
    slug: "tasks",
    layer: "core",
    name: "Tasks",
    depth: "lite",
    badge: "Included",
    status: "Available — follow-ups on contacts and opportunities.",
    headline: "Decide, then do.",
    subhead:
      "Tasks are how recommendations become work. They sit on Contacts and Opportunities — not a separate to-do app.",
    what: "Create, complete and list follow-ups in the operating loop: Decide → Act.",
    connects: "Opportunities, CRM, Automation and Command Centre recommended actions.",
    who: "Teams who need the next action attached to the record, not lost in email.",
    highlight: ["Decide", "Act"],
    related: ["opportunities", "calendar", "automation"],
    included: true,
  }),
  app({
    slug: "calendar",
    layer: "core",
    name: "Calendar",
    depth: "lite",
    badge: "Included",
    status: "Available — bookings and schedule on Core; Industry Apps specialise the diary.",
    headline: "Time belongs on the same platform as the customer.",
    subhead:
      "Appraisals, stays and follow-ups should not live in a personal calendar the platform cannot see.",
    what: "Schedule and bookings connected to Contacts, Opportunities and Industry workflows.",
    connects: "Real Estate appraisals, Accommodation stays, Tasks and Communications.",
    who: "Operators whose day is appointments, not just a pipeline board.",
    highlight: ["Act"],
    related: ["tasks", "real-estate", "accommodation"],
    included: true,
  }),
  app({
    slug: "documents",
    layer: "core",
    name: "Documents",
    depth: "lite",
    badge: "Included",
    status: "Available as files on business records — deeper DMS continues.",
    headline: "Files attached to the work, not a drive beside it.",
    subhead: "Contracts, briefs and assets should sit on the Contact, Opportunity or listing they belong to.",
    what: "Documents linked to Core and Industry records so the operating system has the file, not just a mention of it.",
    connects: "CRM, Opportunities, Real Estate and Accommodation records.",
    who: "Teams tired of searching Slack and email for the latest PDF.",
    highlight: ["Centralise"],
    related: ["crm", "opportunities"],
    included: true,
  }),
  app({
    slug: "communications",
    layer: "core",
    name: "Communications",
    depth: "lite",
    badge: "Included",
    status: "Available — email and message history in context. Voice remains Early Access.",
    headline: "The conversation stays on the record.",
    subhead:
      "If the email lives only in someone’s inbox, the platform cannot Understand or Learn.",
    what: "Email and message history attached to Contacts and Opportunities.",
    connects: "CRM, Automation, Advanced AI Communications (Voice Agents add-on) and Industry follow-up.",
    who: "Operators who need a shared history, not a personal mailbox as the system of record.",
    highlight: ["Connect", "Act"],
    related: ["crm", "ai-communications", "automation"],
    included: true,
  }),
  app({
    slug: "commerce",
    layer: "core",
    name: "Commerce",
    depth: "lite",
    badge: "Early Access",
    status: "Early Access — quotes, invoices and payments rolling out. Not a finished billing suite.",
    headline: "Revenue objects on the same foundation.",
    subhead:
      "Quotes and invoices should close the loop from Opportunity to cash — without a second finance product.",
    what: "Quotes, invoices, products and subscriptions as Core commercial objects.",
    connects: "Opportunities, Contacts, Accommodation payments and platform billing (separate).",
    who: "Founding operators who need to quote and invoice without leaving DigitalGate.",
    highlight: ["Act", "Grow"],
    related: ["opportunities", "crm"],
    included: true,
  }),

  // ——— Infrastructure ———
  app({
    slug: "website",
    layer: "infrastructure",
    name: "Website Connection & Management",
    depth: "lite",
    badge: "Available",
    status: "Available — connect and manage your site with platform context. Depth expands with plan.",
    headline: "Your website is a platform surface — not a brochure on the side.",
    subhead:
      "When the site is connected, CRM, SEO, AI Visibility and Prospecting can see the same presence.",
    what: "Connect, health-check and manage the website that already represents your business.",
    connects: "SEO, AI Visibility, Reputation, Prospecting audits and Industry enquiry capture.",
    who: "Businesses whose site should feed the operating system, not sit in a separate agency login.",
    highlight: ["Connect"],
    related: ["website-builder", "seo", "ai-visibility"],
  }),
  app({
    slug: "website-builder",
    layer: "infrastructure",
    name: "Website Builder",
    depth: "lite",
    badge: "Growth+",
    status: "Growth+ — advanced creation and publishing. Not included in every platform plan.",
    headline: "Build and publish inside the same operating system.",
    subhead:
      "Pages, brand and funnels that can talk to Contacts and Industry Apps — not a standalone CMS clone.",
    what: "Create, edit and publish sites from DigitalGate, with honest progressive capability by plan.",
    connects: "Website Connection, Domains, DNS, SEO and capture funnels.",
    who: "Growth and Scale operators who want the site on the platform, not WordPress plus a CRM.",
    highlight: ["Connect", "Act"],
    related: ["website", "domains", "seo"],
  }),
  app({
    slug: "domains",
    layer: "infrastructure",
    name: "Domains",
    depth: "lite",
    badge: "Early Access",
    status: "Early Access — connect and manage domains from the platform.",
    headline: "Digital identity on the operating system.",
    what: "Search, connect and point domains without treating DNS as a separate vendor relationship.",
    connects: "Website Connection, DNS, Email and Make-it-live checklists.",
    who: "Operators bringing a live domain onto DigitalGate.",
    highlight: ["Connect"],
    related: ["dns", "website", "email"],
  }),
  app({
    slug: "dns",
    layer: "infrastructure",
    name: "DNS",
    depth: "lite",
    badge: "Early Access",
    status: "Early Access — inspect and apply website DNS when the zone is writable.",
    headline: "Records beside the site they serve.",
    what: "DNS console alongside domains and hosting — not a mystery at the registrar.",
    connects: "Domains, Website Connection, Email and SSL (when ready).",
    who: "Teams going live on DigitalGate Infrastructure.",
    highlight: ["Connect"],
    related: ["domains", "website", "email"],
  }),
  app({
    slug: "email",
    layer: "infrastructure",
    name: "Email",
    depth: "lite",
    badge: "Early Access",
    status: "Early Access — mailbox and transactional email infrastructure, rolling out honestly.",
    headline: "Mail that the platform can see.",
    what: "Infrastructure for sending and receiving in context of the business — not a consumer inbox product.",
    connects: "Communications, Domains, DNS and Automation.",
    who: "Organisations ready to stop treating email as a silo.",
    highlight: ["Connect", "Act"],
    related: ["communications", "domains", "automation"],
  }),
  app({
    slug: "hosting",
    layer: "infrastructure",
    name: "Hosting",
    depth: "soon",
    badge: "Coming Soon",
    status: "Coming Soon — hosting abstraction as it becomes commercially ready. Not sold as a standalone host today.",
    headline: "Presence without a separate hosting company.",
    what: "Managed hosting for DigitalGate sites when the product is ready to sell — not a promise of cPanel.",
    connects: "Website Builder, Domains, SSL, Backups and Cloudflare.",
    who: "Future operators who want site + OS from one vendor.",
    related: ["website-builder", "ssl", "backups"],
  }),
  app({
    slug: "ssl",
    layer: "infrastructure",
    name: "SSL",
    depth: "soon",
    badge: "Coming Soon",
    status: "Coming Soon — certificates managed with your site.",
    headline: "Trust, attached to the domain.",
    what: "SSL as Infrastructure, not a checkbox you chase at the registrar.",
    connects: "Domains, Hosting and Website Connection.",
    who: "Sites going live on DigitalGate when this ships.",
    related: ["domains", "hosting"],
  }),
  app({
    slug: "backups",
    layer: "infrastructure",
    name: "Backups",
    depth: "soon",
    badge: "Coming Soon",
    status: "Coming Soon — backup and restore for managed presence.",
    headline: "Recover the site the platform actually runs.",
    what: "Backups for DigitalGate-managed presence — not a generic backup SKU yet.",
    connects: "Hosting, Website Builder and Website Connection.",
    who: "Operators on managed Infrastructure once commercially ready.",
    related: ["hosting", "website-builder"],
  }),
  app({
    slug: "cloudflare",
    layer: "infrastructure",
    name: "Cloudflare",
    depth: "soon",
    badge: "Coming Soon",
    status: "Coming Soon — CDN and edge controls when ready.",
    headline: "Edge, without a second control panel story.",
    what: "Cloudflare as an Infrastructure capability when DigitalGate can operate it honestly.",
    connects: "Hosting, DNS, SSL and Website Connection.",
    who: "Sites that need edge performance as part of the OS.",
    related: ["hosting", "dns"],
  }),


  // ——— Industry Apps (commercial verticals) ———
  app({
    slug: "property",
    layer: "industry",
    name: "Property",
    depth: "full",
    badge: "Available",
    kind: "industry-app",
    commercialStatus: "AVAILABLE · +$99/mo · 1 Template included",
    status:
      "Property Industry App — one connected property operating platform. Activate Templates for how you sell, manage or develop.",
    headline: "One Property Industry App. Specialise with Templates.",
    subhead:
      "You buy Property once (+$99/mo). Real Estate, Property Management, Commercial, Development and Buyers Agency are Templates — not separate Industry Apps.",
    what: "Property transactions, ownership and development workflows on DigitalGate Core. Short-stay hospitality lives under Hospitality & Accommodation — not here.",
    connects: "CRM, Opportunities, Documents, Commerce, Growth Apps and the Digital Twin™ share the same property context.",
    who: "Agencies, PMs, commercial operators and developers who want one property OS — starting with Real Estate as the founding Template.",
    templates: [
      { name: "Real Estate", status: "Available", href: "/apps/industry/real-estate/" },
      { name: "Property Management", status: "Coming Soon", href: "/apps/industry/property-management/" },
      { name: "Commercial Property", status: "Coming Soon", href: "/apps/industry/commercial-property/" },
      { name: "Property Development", status: "Later", href: "/apps/industry/property-development/" },
      { name: "Buyers Agency", status: "Soon", href: "/apps/industry/property/" },
      { name: "Valuation / Property Advisory", status: "Future", href: "/apps/industry/property/" },
    ],
    pricing:
      "Property Industry +$99/mo · 1 Template included · +$29/mo each additional Template. Platform subscription required.",
    related: ["real-estate", "crm", "opportunities"],
  }),
  app({
    slug: "hospitality-accommodation",
    layer: "industry",
    name: "Hospitality & Accommodation",
    depth: "full",
    badge: "Early Access",
    kind: "industry-app",
    commercialStatus: "EARLY ACCESS · +$99/mo · 1 Template included",
    status:
      "Hospitality & Accommodation Industry App — stays, venues and hospitality groups. Accommodation belongs here, not under Property.",
    headline: "Stays and hospitality on the same operating system.",
    subhead:
      "One Industry App (+$99/mo). Short-Stay Accommodation, Hotels, F&B and Venues are Templates — not separate products.",
    what: "Bookings, guests, availability, housekeeping and hospitality operations on Core Contacts and Calendar.",
    connects: "Guests are Contacts. Stays create work. Reviews, Website and Growth Apps see the same business.",
    who: "Short-stay operators (including Currumbin Valley Hideaway) — Short-Stay Accommodation Template in early access.",
    templates: [
      { name: "Short-Stay Accommodation", status: "Early Access", href: "/apps/industry/accommodation/" },
      { name: "Hotels · Motels · Resorts", status: "Coming Soon", href: "/apps/industry/hospitality-accommodation/" },
      { name: "Restaurants & Cafés", status: "Future", href: "/apps/industry/hospitality-accommodation/" },
      { name: "Bars & Venues", status: "Future", href: "/apps/industry/hospitality-accommodation/" },
      { name: "Hospitality Groups", status: "Future", href: "/apps/industry/hospitality-accommodation/" },
    ],
    pricing:
      "Hospitality & Accommodation +$99/mo · 1 Template included · +$29/mo each additional. Platform subscription required.",
    related: ["accommodation", "crm", "reputation"],
  }),

  // ——— Templates under Property / Hospitality (detail pages; not separate Industry SKUs) ———
  app({
    slug: "real-estate",
    layer: "industry",
    name: "Real Estate",
    depth: "full",
    badge: "Property Template",
    kind: "template",
    parentIndustry: "property",
    parentIndustryLabel: "Property",
    commercialStatus: "PROPERTY TEMPLATE · AVAILABLE",
    status:
      "Flagship Template under the Property Industry App. Live on Roe Realty and available to selected Founding Customers.",
    headline: "Turn your sales pipeline into an operating system.",
    subhead:
      "Vendors, buyers, appraisals and listings are the Real Estate Template — not a separate Industry App. Buy Property, activate Real Estate.",
    what: "Residential sales workflow: vendors, buyers, appraisals, listings and settlements on shared Core Contacts and Opportunities.",
    connects:
      "Every listing, lead and appraisal writes Core objects. Growth Apps then see the same pipeline.",
    who: "Australian sales agencies — starting with operators already on DigitalGate (including Roe Realty).",
    highlight: ["Connect", "Centralise", "Understand", "Decide", "Act", "Grow"],
    flow: [
      "Lead",
      "Contact",
      "Opportunity",
      "Appraisal",
      "Listing",
      "Buyer activity",
      "Deal",
      "Revenue",
    ],
    objects: [
      "Vendor lead",
      "Buyer lead",
      "Property / appraisal",
      "Listing",
      "Contact",
      "Opportunity",
      "Task",
    ],
    notThis:
      "Not four products (Vendor CRM, Buyer CRM, Appraisals, Listings). Not a standalone Industry App — it is a Property Template.",
    whatYouGet: [
      "Vendor Lead Pipeline",
      "Buyer Lead Pipeline",
      "Appraisal Management",
      "Listing Management",
      "Buyer Activity",
      "Tasks & Follow-up",
      "Opportunity Management",
      "Settlement / Deal Tracking",
      "Connected CRM records",
      "Automation across the workflow",
      "AI and Growth Apps on the same data",
    ],
    builtFor: [
      "Boutique real estate agencies",
      "Independent agencies",
      "Sales teams",
      "Property-focused businesses",
    ],
    builtForNote: "Designed for Australian real estate operations.",
    productionProof: {
      intro:
        "The Real Estate Template operates on DigitalGate through Roe Realty — the production reference for Founding Customers.",
      reference: {
        name: "Roe Realty",
        label: "Property · Real Estate Template · Production Reference",
      },
      items: [
        { name: "Vendor Pipeline", status: "Live" },
        { name: "Property & Appraisal Workflow", status: "Live" },
        { name: "Buyer Management", status: "Live / developing" },
      ],
    },
    pricing:
      "Included with Property Industry (+$99/mo) as your first Template · additional Templates +$29/mo. Platform subscription required.",
    keywords: [
      "real estate CRM",
      "property industry app",
      "vendor leads",
      "buyer CRM",
      "appraisal software",
    ],
    related: ["property", "crm", "opportunities", "prospecting", "ai-visibility"],
  }),
  app({
    slug: "accommodation",
    layer: "industry",
    name: "Accommodation",
    depth: "full",
    badge: "Hospitality Template",
    kind: "template",
    parentIndustry: "hospitality-accommodation",
    parentIndustryLabel: "Hospitality & Accommodation",
    commercialStatus: "HOSPITALITY TEMPLATE · EARLY ACCESS",
    status:
      "Short-Stay Template under Hospitality & Accommodation — bookings, units, calendar and housekeeping with founding properties.",
    headline: "Direct stays without a second guest database.",
    subhead:
      "Not a Property App. Not a standalone Industry product. Activate Accommodation under Hospitality & Accommodation.",
    what: "Units, availability, stay bookings, guests, housekeeping and payments for short-stay.",
    connects:
      "Guests are Contacts. Stays create operational work. Reviews and Growth Apps see the same business.",
    who: "Founding hospitality operators (including Currumbin Valley Hideaway).",
    pricing:
      "Included with Hospitality & Accommodation Industry (+$99/mo) as a Template · additional Templates +$29/mo.",
    highlight: ["Connect", "Centralise", "Act", "Learn", "Grow"],
    flow: [
      "Enquiry",
      "Guest (Contact)",
      "Stay",
      "Calendar",
      "Housekeeping",
      "Review",
      "Direct booking",
      "Revenue",
    ],
    objects: ["Unit", "Stay booking", "Guest Contact", "Calendar block", "Payment"],
    notThis:
      "Not Lodgify. Not under Property. Channel sync serves the operating system — guests become Contacts.",
    related: ["hospitality-accommodation", "crm", "calendar", "reputation", "website"],
  }),

  // ——— Other Industry Apps ———
  app({
    slug: "services",
    layer: "industry",
    name: "Services",
    depth: "full",
    badge: "Available",
    kind: "industry-app",
    commercialStatus: "AVAILABLE · +$99/mo · Templates for trades",
    status:
      "Services Industry App — jobs, quotes and scheduling. Templates customise trades (never Electrician App / Plumber App).",
    headline: "One Services App. Templates for how you work.",
    subhead:
      "+$99/mo Industry · Templates for Electrical, Plumbing, Cleaning, Construction and more — not dozens of top-level Apps.",
    what: "Jobs, scheduling and quotes for field and service businesses on Core CRM and Commerce.",
    connects: "Contacts, Tasks, Calendar, Commerce. Templates specialise terminology and workflow.",
    who: "Trades and service operators ready for a connected operating platform.",
    templates: [
      { name: "Trades / General", status: "Available", href: "/apps/industry/services/" },
      { name: "Electrical · Plumbing · HVAC", status: "Soon", href: "/apps/industry/services/" },
      { name: "Cleaning · Maintenance · Field", status: "Soon", href: "/apps/industry/services/" },
      { name: "Construction · Facilities", status: "Coming Soon", href: "/apps/industry/services/" },
    ],
    pricing: "Services Industry +$99/mo · 1 Template included · +$29/mo each additional.",
    related: ["crm", "commerce", "calendar"],
  }),
  app({
    slug: "property-management",
    layer: "industry",
    name: "Property Management",
    depth: "soon",
    badge: "Property Template",
    kind: "template",
    parentIndustry: "property",
    parentIndustryLabel: "Property",
    status: "Coming Soon — Property Template for long-term rentals (owners, tenants, leases). Not a separate Industry App.",
    headline: "Rent rolls as a Property Template — when ready.",
    what: "Owners, tenants, leases, maintenance and arrears under the Property Industry App.",
    connects: "Shares Contacts, Documents, Tasks and Commerce with Core. Distinct from Real Estate sales Template.",
    who: "Agencies and PMs who want one Property Industry — register interest.",
    related: ["property", "real-estate", "commercial-property"],
  }),
  app({
    slug: "commercial-property",
    layer: "industry",
    name: "Commercial Property",
    depth: "soon",
    badge: "Property Template",
    kind: "template",
    parentIndustry: "property",
    parentIndustryLabel: "Property",
    status: "Coming Soon — Property Template for commercial sales and leasing. Not a separate Industry App.",
    headline: "Commercial workflows under Property.",
    what: "Commercial assets, leasing and landlord/tenant records when built.",
    connects: "Same Contacts and Opportunities model as Real Estate Template — different objects.",
    who: "Commercial operators planning ahead.",
    related: ["property", "real-estate", "property-management"],
  }),
  app({
    slug: "property-development",
    layer: "industry",
    name: "Property Development",
    depth: "soon",
    badge: "Property Template",
    kind: "template",
    parentIndustry: "property",
    parentIndustryLabel: "Property",
    status: "Later — Property Template. Architecture reserved. Not a separate Industry App.",
    headline: "Projects, lots and stages — later under Property.",
    what: "Development projects on the Property Industry App when the time comes.",
    connects: "Will sit with sales and PM Templates on the same Property Industry.",
    who: "Developers mapping the ecosystem — not a product to buy today.",
    related: ["property", "real-estate", "commercial-property"],
  }),
  app({
    slug: "finance",
    layer: "industry",
    name: "Finance",
    depth: "soon",
    badge: "Early Access",
    kind: "industry-app",
    status: "Early Access roadmap — Accounting first; broking, planning, insurance Templates follow. Not an “Accounting App”.",
    headline: "Money relationships on one Industry App.",
    subhead: "Accountants → Finance → Accounting Template. Brokers and advisers are Templates too.",
    what: "Finance Industry App with Templates for Accounting, Broking, Planning, Insurance and Advisory.",
    connects: "Contacts, Opportunities, Documents and Communications.",
    templates: [
      { name: "Accounting & Bookkeeping", status: "Early Access", href: "/apps/industry/finance/" },
      { name: "Finance / Mortgage Broking", status: "Coming Soon", href: "/apps/industry/finance/" },
      { name: "Financial Planning · Insurance", status: "Coming Soon", href: "/apps/industry/finance/" },
    ],
    pricing: "Finance Industry +$99/mo · 1 Template included · +$29/mo each additional.",
    who: "Accountants and finance professionals registering interest.",
    related: ["crm", "opportunities", "prospecting"],
  }),
  app({
    slug: "automotive",
    layer: "industry",
    name: "Automotive",
    depth: "soon",
    badge: "Coming Soon",
    kind: "industry-app",
    status: "Coming Soon — dealerships, workshops and auto services as Templates under one Industry App.",
    headline: "Stock and service without a dealer-only island.",
    what: "Automotive Industry App with Templates for Dealerships, Mechanical, Auto Electrical and more.",
    connects: "Contacts, Opportunities, Calendar and Communications.",
    templates: [
      { name: "Dealerships / Sales", status: "Coming Soon", href: "/apps/industry/automotive/" },
      { name: "Workshops · Mechanical", status: "Coming Soon", href: "/apps/industry/automotive/" },
    ],
    who: "Dealers and workshops planning on DigitalGate later.",
    related: ["crm", "opportunities"],
  }),
  app({
    slug: "creator",
    layer: "industry",
    name: "Creator & Media",
    depth: "soon",
    badge: "Early Access",
    kind: "industry-app",
    status: "Early Access interest — audience, content and studio Templates under one Industry App.",
    headline: "Creators and media on Core — when ready.",
    what: "Creator & Media Industry with Templates for Creators, Music, Media and Personal Brands.",
    connects: "Contacts, Commerce, Social and Communications.",
    templates: [
      { name: "Creators · Personal Brands", status: "Early Access", href: "/apps/industry/creator/" },
      { name: "Music · Media · Production", status: "Coming Soon", href: "/apps/industry/creator/" },
    ],
    pricing: "Creator & Media +$99/mo · 1 Template included · +$29/mo each additional.",
    who: "Creators and media businesses registering founding interest.",
    related: ["crm", "commerce", "social"],
  }),

  // ——— Growth · full ———
  app({
    slug: "ai-visibility",
    layer: "growth",
    name: "AI Visibility",
    depth: "full",
    badge: "Available",
    status: "Available as a Growth App add-on. Scores use observable website signals — not invented ChatGPT rankings.",
    headline: "Be findable where buyers now ask questions.",
    subhead:
      "AI Visibility is not a consultancy SKU. It is how DigitalGate Understands whether your presence is structured for search and AI systems — then tells you what to Act on.",
    what: "Readiness for Google and AI search from live presence signals (schema, entity, technical) shared with SEO.",
    connects:
      "Website Connection, SEO Engine, Prospecting audits and the Digital Twin. Findings become Opportunities and Tasks — not a PDF that dies in email.",
    who: "Founding operators who already have a site on or connected to DigitalGate and need a honest visibility story.",
    highlight: ["Understand", "Decide", "Grow"],
    flow: [
      "Website connected",
      "Presence signals",
      "AI Visibility score",
      "Gaps",
      "Recommended action",
      "Task or content change",
      "Re-measure",
    ],
    objects: ["Website", "Presence audit", "Opportunity", "Task"],
    notThis:
      "Not “we will get you cited by ChatGPT.” We measure what we can observe. That honesty is the product.",
    related: ["seo", "prospecting", "website", "automation"],
  }),
  app({
    slug: "seo",
    layer: "growth",
    name: "SEO",
    depth: "full",
    badge: "Available",
    status: "Available as a Growth App add-on. Same presence audit as AI Visibility — different job.",
    headline: "Technical and content truth, on the platform that owns the site.",
    subhead:
      "SEO here is not an agency retainer. It is how DigitalGate Understands the site you already run, then feeds Decide → Act.",
    what: "Audits, technical signals and optimisation guidance from the live site — one source of truth with AI Visibility.",
    connects:
      "Website Connection / Builder, AI Visibility, Prospecting, Real Estate landing pages and Automation follow-through.",
    who: "Founding businesses whose growth depends on being found — especially local services and Real Estate.",
    highlight: ["Understand", "Act", "Learn"],
    flow: [
      "Site connected",
      "Audit",
      "Issues",
      "Fix or task",
      "Publish",
      "Re-audit",
      "Learn",
    ],
    objects: ["Website", "SEO audit", "Task", "Page"],
    notThis:
      "Not a ranking guarantee and not a separate SEO company. If the audit cannot become a Task on a Contact or Opportunity, it is theatre.",
    related: ["ai-visibility", "website", "prospecting", "real-estate"],
  }),
  app({
    slug: "automation",
    layer: "growth",
    name: "Automation",
    depth: "full",
    badge: "Available",
    status: "Available — workflows across Core and Apps. Listed here as the commercial Act surface.",
    headline: "When the platform knows what to do, it should do it.",
    subhead:
      "Automation is how DigitalGate Acts. It is not a Zapier clone in the Apps aisle. Rules fire on Core events — leads, opportunities, payments, stays — so people are not the integration layer.",
    what: "Triggers, multi-step workflows and logs that move work from Decide to Act: create tasks, send communications, advance opportunities.",
    connects:
      "CRM, Opportunities, Real Estate, Accommodation, Commerce, Communications and Growth signals. The Event Bus is platform; this App is how operators shape it.",
    who: "Founding operators who have real records and need the next step to happen without another spreadsheet.",
    highlight: ["Decide", "Act", "Learn"],
    flow: [
      "Event",
      "Rule",
      "Action",
      "Task / message / stage",
      "Outcome",
      "Log",
      "Improve the rule",
    ],
    objects: ["Automation rule", "Event", "Task", "Communication", "Opportunity"],
    notThis:
      "Not “buy Automation because other CRMs have it.” If a workflow does not change a Core object, it is decoration.",
    related: ["opportunities", "prospecting", "communications", "crm"],
  }),
  app({
    slug: "prospecting",
    layer: "growth",
    name: "Prospecting & Opportunity Engine",
    depth: "full",
    badge: "Available",
    status:
      "Available as a Growth App (+$99/mo). One App — Prospecting, Discovery, Opportunity scoring, Pipeline, Activity, AI recommendations, Digital Presence and CRM handoff. Not separate SKUs.",
    headline: "Find the opportunities your business should act on next.",
    subhead:
      "This is the Understand → Decide → Act product. Discovery finds businesses. Presence and platform signals score them. The Opportunity Engine ranks what to do. Automation can act. That is not a CRM feature list — it is the DigitalGate thesis.",
    what: "Prospect discovery (Places + ABN when configured), digital presence signals, Fit × Need × Reachability × Commercial × Weakness scoring, pipeline, activity, AI next-best-action and CRM conversion — one Growth App.",
    connects:
      "Combines prospect discovery, website and Google signals, AI Visibility, CRM history, lead and opportunity scoring, recommended actions and automated outreach as those pieces are ready. Qualified prospects become Contacts, Companies and Opportunities — not a silent CRM dump.",
    who: "Commercial lending, agency and local-service operators who need a pipeline of who to speak to next — then follow through inside the same CRM + Opportunity + AI ecosystem.",
    highlight: ["Understand", "Decide", "Act", "Learn", "Grow"],
    flow: [
      "Prospect",
      "Discovery",
      "Opportunity score",
      "CRM",
      "Pipeline",
      "AI recommendation",
      "Follow-up",
      "Conversion",
    ],
    objects: [
      "Discovery candidate",
      "Growth prospect",
      "Presence audit",
      "Opportunity",
      "Recommended action",
      "Task",
    ],
    pricing:
      "Prospecting & Opportunity Engine +$99/mo — optional Growth App, billed separately (Prospecting, Discovery and Opportunity Engine included in this one App).",
    notThis:
      "Not “we have a CRM, so we prospect.” CRM stores the relationship. This App decides who deserves attention — then the rest of DigitalGate can Act and Learn.",
    keywords: [
      "opportunity engine",
      "prospect discovery",
      "ABN lookup",
      "lead scoring",
      "business intelligence",
    ],
    related: ["opportunities", "ai-visibility", "seo", "automation", "crm"],
  }),

  // ——— Growth · lite ———
  app({
    slug: "analytics",
    layer: "growth",
    name: "Analytics",
    depth: "lite",
    badge: "Early Access",
    status: "Early Access — KPI snapshots and connectors. Honest empty states when data is missing.",
    headline: "Measure so the loop can Learn.",
    what: "Reporting and connectors so DigitalGate can see performance — not a vanity dashboard.",
    connects: "Website, Commerce, Industry Apps and Opportunity outcomes.",
    who: "Operators who want Learn → Grow without exporting to another BI tool first.",
    highlight: ["Learn", "Grow"],
    related: ["seo", "opportunities", "commerce"],
  }),
  app({
    slug: "social",
    layer: "growth",
    name: "Social",
    depth: "lite",
    badge: "Early Access",
    status: "Early Access — publish and manage social from the platform. Depth continues.",
    headline: "Distribution attached to the same customers.",
    what: "Social publishing as a Growth capability — not a Hootsuite replacement claim.",
    connects: "Contacts, Marketing, Reputation and Website.",
    who: "Teams who want social on the OS, knowing it is still early.",
    highlight: ["Act", "Grow"],
    related: ["reputation", "ai-communications", "website"],
  }),
  app({
    slug: "reputation",
    layer: "growth",
    name: "Reputation",
    depth: "lite",
    badge: "Free",
    status: "Free Growth App — review inbox and requests. Score only when real data exists. No separate charge.",
    headline: "What customers say, on the record.",
    what: "Reviews and reputation as a Free Growth App on Core review plumbing — no invented scores.",
    connects: "Accommodation stays, Real Estate settlements, Contacts and AI Visibility context.",
    who: "Operators who already collect reviews and want them inside DigitalGate.",
    pricing: "Reputation is Free — included with the platform; no Growth App charge.",
    highlight: ["Learn", "Grow"],
    related: ["accommodation", "ai-communications", "analytics"],
  }),
  app({
    slug: "ai-communications",
    layer: "growth",
    name: "AI Voice Agents",
    depth: "lite",
    badge: "Early Access",
    status:
      "Early Access — Advanced AI Communications under Core Communications. Voice Agents still in development — not a live call-centre product. Not a separate Growth App.",
    headline: "Advanced communications under Core — not a Growth App silo.",
    what: "AI Voice Agents, Call Centre and related capabilities as a Core Communications add-on (voice_ai).",
    connects: "Communications, Contacts, Automation and Knowledge.",
    who: "Founding teams who want advanced AI assistance now and voice later — without overclaiming.",
    highlight: ["Act"],
    related: ["communications", "automation", "crm"],
  }),
];

export function hrefFor(app) {
  return `/apps/${app.layer}/${app.slug}/`;
}

export function appBySlug(slug) {
  return APPS.find((a) => a.slug === slug);
}

export function appsInLayer(layerId) {
  return APPS.filter((a) => a.layer === layerId);
}
