export {
  DREAMSCAPE_DEFAULT_RESELLER_ID_HEADER,
  DREAMSCAPE_RESELLER_ID_HEADERS,
  buildDreamscapeAuthHeaders,
  dreamscapeAuthHeaders,
  dreamscapeRequestId,
  dreamscapeSignature,
  type DreamscapeAuthHeaderOptions,
  type DreamscapeAuthHeadersResult,
} from "./auth";
export {
  DREAMSCAPE_PROD_BASE_URL,
  DREAMSCAPE_SANDBOX_BASE_URL,
  DreamscapeApiError,
  describeDreamscapeAuthFailure,
  dreamscapeEnvPresence,
  dreamscapeFetch,
  isDreamscapeApiKeyFormatValid,
  isDreamscapeConfigured,
  normalizeDreamscapeApiKey,
  normalizeDreamscapeResellerId,
  resetDreamscapeProxyDispatcherCache,
  parseDreamscapeSoapEnv,
  resolveDreamscapeApiMode,
  resolveDreamscapeConfig,
  resolveDreamscapeHttpsProxy,
  resolveDreamscapeResellerIdHeader,
  resolveDreamscapeSoapEndpoint,
  sanitizeDreamscapeBodySnippet,
  serializeDreamscapeSearchParams,
  shouldSendDreamscapeResellerId,
  soapHostFromEndpoint,
  type DreamscapeApiMode,
  type DreamscapeEnvPresence,
  type DreamscapeRequestDebug,
  type DreamscapeSoapEnv,
} from "./client";
export {
  DreamscapeDomainProvider,
  DreamscapeProvider,
} from "./domain-provider";
export {
  DREAMSCAPE_SOAP_DOMAIN_CHECK_ACTION,
  DREAMSCAPE_SOAP_GET_BALANCE_ACTION,
  DREAMSCAPE_SOAP_NS,
  DREAMSCAPE_SOAP_PROD_ENDPOINT,
  DREAMSCAPE_SOAP_PROD_WSDL,
  DREAMSCAPE_SOAP_SANDBOX_ENDPOINT,
  DREAMSCAPE_SOAP_SANDBOX_WSDL,
  DreamscapeSoapError,
  buildDomainCheckEnvelope,
  buildGetBalanceEnvelope,
  dreamscapeSoapDomainCheck,
  dreamscapeSoapGetBalance,
  extractSoapFault,
  isDreamscapeSoapSandboxEndpoint,
  normalizeDreamscapeSoapEndpoint,
  parseDomainCheckResponse,
  soapResponseIndicatesAuthFailure,
  type DreamscapeSoapAvailabilityItem,
} from "./soap";
export {
  DREAMSCAPE_SOAP_CONTACT_CREATE_ACTION,
  DREAMSCAPE_SOAP_DOMAIN_CREATE_ACTION,
  DREAMSCAPE_SOAP_DOMAIN_DNS_UPDATE_ACTION,
  DREAMSCAPE_SOAP_DOMAIN_INFO_ACTION,
  DREAMSCAPE_SOAP_DOMAIN_RENEW_ACTION,
  DREAMSCAPE_SOAP_TRANSFER_START_ACTION,
  domainNeedsAuEligibility,
  dreamscapeSoapContactCreate,
  dreamscapeSoapDomainCreate,
  dreamscapeSoapDomainDnsUpdate,
  dreamscapeSoapDomainInfo,
  dreamscapeSoapDomainRenew,
  dreamscapeSoapTransferStart,
  type SoapContactCreateParams,
  type SoapDomainCreateParams,
  type SoapDomainDetails,
  type SoapEligibility,
} from "./soap-ops";
export {
  DREAMSCAPE_WEBHOOK_PATH,
  clearDreamscapeWebhookEvents,
  dreamscapeNotificationUrl,
  extractDreamscapeWebhookSecret,
  handleDreamscapeWebhookPayload,
  handleDreamscapeWebhookPayloadAsync,
  isDreamscapeWebhookConfigured,
  listDreamscapeWebhookEvents,
  listDreamscapeWebhookEventsAsync,
  resolveDreamscapeWebhookSecret,
  verifyDreamscapeWebhookRequest,
  type DreamscapeWebhookEventKind,
  type DreamscapeWebhookEventStub,
  type HandleDreamscapeWebhookResult,
} from "./webhooks";
