"use client";

import Link from "next/link";
import type { ReactNode } from "react";

import { SetupProgressBar } from "@/components/overview/SetupProgressBar";
import type { BusinessOverview, OverviewInsight } from "@dg/platform-core";

function StatusDot({ status }: { status: string }) {
  const colour = status === "healthy" || status === "connected" || status === "online" ? "bg-emerald-400" : status === "warning" ? "bg-amber-400" : "bg-slate-500";
  return <span className={`inline-block h-2 w-2 rounded-full ${colour}`} />;
}
function confidenceLabel(confidence: BusinessOverview["healthConfidence"]) { if (confidence === "high") return "High confidence"; if (confidence === "medium") return "Medium confidence"; if (confidence === "low") return "Low confidence"; return "Insufficient evidence"; }
function insightTone(insight: OverviewInsight) { if (insight.tone === "warning") return "border-amber-500/25 bg-amber-500/5 text-amber-100"; if (insight.tone === "positive") return "border-emerald-500/25 bg-emerald-500/5 text-emerald-100"; return "border-slate-700/80 bg-slate-950/40 text-slate-200"; }

function HealthTrendChart({ values }: { values: number[] }) {
  if (values.length < 2) return <div className="flex min-h-56 items-center justify-center rounded-2xl border border-dashed border-slate-700 bg-slate-950/30 px-6 text-center"><div><p className="text-sm font-medium text-slate-200">Building your real trend</p><p className="mt-2 max-w-sm text-xs leading-relaxed text-slate-500">DigitalGate will draw this chart only from persisted Business Health measurements. No synthetic history is generated.</p></div></div>;
  const width=680,height=230,padX=28,padTop=22,padBottom=30,minValue=Math.max(0,Math.min(...values)-6),maxValue=Math.min(100,Math.max(...values)+6),range=Math.max(1,maxValue-minValue),plotHeight=height-padTop-padBottom,plotWidth=width-padX*2;
  const coords=values.map((value,index)=>({x:padX+(index/Math.max(values.length-1,1))*plotWidth,y:padTop+(1-(value-minValue)/range)*plotHeight,value}));
  const linePoints=coords.map((point)=>`${point.x},${point.y}`).join(" "),areaPoints=`${padX},${height-padBottom} ${linePoints} ${width-padX},${height-padBottom}`,latest=coords[coords.length-1],first=values[0],delta=values[values.length-1]-first;
  return <div><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><p className="text-3xl font-semibold text-white">{latest.value}<span className="text-base font-normal text-slate-500"> / 100</span></p><p className={`mt-1 text-xs ${delta>=0?"text-emerald-300":"text-amber-300"}`}>{delta>=0?"↑":"↓"} {Math.abs(delta)} points across recorded measurements</p></div><p className="text-xs text-slate-500">{values.length} real measurement{values.length===1?"":"s"}</p></div><div className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-950/45 px-2 py-2"><svg viewBox={`0 0 ${width} ${height}`} className="h-56 w-full" role="img" aria-label="Business Health recorded trend"><defs><linearGradient id="healthArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="currentColor" stopOpacity="0.22"/><stop offset="100%" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs>{[0,.25,.5,.75,1].map((fraction)=>{const y=padTop+fraction*plotHeight,label=Math.round(maxValue-fraction*range);return <g key={fraction}><line x1={padX} y1={y} x2={width-padX} y2={y} stroke="currentColor" className="text-slate-800" strokeWidth="1"/><text x="2" y={y+4} className="fill-slate-600 text-[10px]">{label}</text></g>})}<polygon points={areaPoints} fill="url(#healthArea)" className="text-emerald-400"/><polyline points={linePoints} fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" className="text-emerald-400"/>{coords.map((point,index)=><g key={`${point.x}-${point.y}`}><circle cx={point.x} cy={point.y} r={index===coords.length-1?5:3.5} className="fill-slate-950 stroke-emerald-400" strokeWidth="2"/>{index===coords.length-1?<text x={point.x-4} y={Math.max(14,point.y-12)} textAnchor="end" className="fill-emerald-300 text-[11px] font-semibold">{point.value}</text>:null}</g>)}</svg></div></div>;
}
function GoalRow({goal}:{goal:BusinessOverview["goals"][number]}){const content=<><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-medium text-white">{goal.title}</p><p className="mt-1 text-xs text-slate-500">{goal.currentLabel} of {goal.targetLabel}</p></div><span className="text-lg font-semibold text-sky-300">{goal.percent}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-sky-500 transition-all" style={{width:`${Math.max(0,Math.min(100,goal.percent))}%`}}/></div></>;return goal.href?<Link href={goal.href} className="block rounded-xl border border-slate-800 bg-slate-950/35 p-4 transition hover:border-sky-500/35">{content}</Link>:<div className="rounded-xl border border-slate-800 bg-slate-950/35 p-4">{content}</div>}
function PulseCard({label,value,href,detail}:{label:string;value:string;href?:string;detail?:string}){const body=<><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight text-white">{value}</p>{detail?<p className="mt-1 text-xs text-slate-500">{detail}</p>:null}</>;return href?<Link href={href} className="rounded-2xl border border-slate-800 bg-slate-950/45 px-4 py-4 transition hover:border-sky-500/35 hover:bg-slate-900/60">{body}</Link>:<div className="rounded-2xl border border-slate-800 bg-slate-950/45 px-4 py-4">{body}</div>}

export function BusinessOverviewDashboard({overview,workspaceSetup,growthScorecard}:{overview:BusinessOverview;workspaceSetup?:ReactNode;growthScorecard?:ReactNode}){
  const priorityCount=overview.priorities.length,firstInsight=overview.insights[0]??null,supportingInsights=overview.insights.slice(1,4),visibleTimeline=overview.timeline.filter((item)=>item.id!=="empty").slice(0,5),snapshotPulse=overview.snapshot.slice(0,3),evidenceCoverage=overview.healthEvidenceCoveragePercent,confidence=confidenceLabel(overview.healthConfidence);
  return <div className="space-y-7">
    <section className="relative overflow-hidden rounded-[1.75rem] border border-violet-500/20 bg-[radial-gradient(circle_at_top_right,rgba(124,58,237,0.18),transparent_34%),linear-gradient(135deg,rgba(15,23,42,0.98),rgba(2,6,23,0.98))] px-5 py-6 shadow-2xl shadow-black/10 sm:px-7 sm:py-7"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-full bg-violet-500/10 blur-3xl" aria-hidden/><div className="relative"><div className="flex flex-wrap items-center justify-between gap-3"><div className="inline-flex items-center gap-2 rounded-full border border-violet-400/20 bg-violet-500/10 px-3 py-1.5"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-violet-500/20 text-[10px] font-bold tracking-wide text-violet-200">AI</span><span className="text-xs font-semibold uppercase tracking-[0.18em] text-violet-200">Aida</span></div><p className="text-xs text-slate-500">Updated {overview.lastUpdatedLabel}</p></div><div className="mt-6 max-w-4xl"><p className="text-sm font-medium text-violet-200/90">{overview.greeting}.</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white sm:text-4xl">{priorityCount>0?`Here${priorityCount===1?"'s":" are"} ${priorityCount===1?"the thing":`${priorityCount} things`} I’d focus on next.`:"Here’s how the business is looking right now."}</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-slate-300 sm:text-base">{overview.dailyBriefing}</p></div><div className="mt-6 flex flex-wrap gap-3"><Link href="/dashboard/advisor" className="rounded-full bg-violet-600 px-5 py-2.5 text-sm font-semibold text-white shadow-lg shadow-violet-950/30 transition hover:bg-violet-500">Ask Aida →</Link>{priorityCount>0?<a href="#todays-priorities" className="rounded-full border border-slate-700 bg-slate-950/40 px-5 py-2.5 text-sm font-semibold text-slate-200 transition hover:border-slate-500">View today&apos;s priorities</a>:null}<Link href="/dashboard/brain" className="rounded-full border border-slate-700 bg-slate-950/40 px-5 py-2.5 text-sm font-semibold text-slate-200 transition hover:border-slate-500">Business Brain</Link></div><div className="mt-6 flex flex-wrap items-center gap-x-5 gap-y-2 border-t border-white/5 pt-5 text-xs text-slate-500"><span>{overview.organisationName}</span>{evidenceCoverage!=null?<span>{evidenceCoverage}% evidence coverage</span>:null}{overview.healthConfidence?<span>{confidence}</span>:null}{overview.healthMeasurementCount!=null?<span>{overview.healthMeasurementCount} recorded Health measurement{overview.healthMeasurementCount===1?"":"s"}</span>:null}</div></div></section>
    {!overview.scoresLive?<div className="rounded-xl border border-blue-500/20 bg-blue-500/5 px-4 py-3 text-sm text-blue-200/90">Aida is still learning this business. Connect the services you use so she can build a reliable Business Health view. <Link href="/dashboard/settings/connected-services" className="font-medium underline hover:text-white">Connected Services →</Link></div>:null}
    {overview.setupProgress.complete?null:<SetupProgressBar progress={overview.setupProgress}/>} {workspaceSetup}
    {overview.setupIncomplete?<div className="rounded-xl border border-amber-500/30 bg-amber-500/5 px-4 py-3 text-sm text-amber-100">Add your first CRM contact to unlock pipeline KPIs. <Link href="/apps/crm/contacts" className="font-medium underline">Add contact →</Link></div>:null}
    <section><div className="mb-3 flex items-end justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">Executive pulse</p><h2 className="mt-1 text-lg font-semibold text-white">The business at a glance</h2></div></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><PulseCard label="Business Health" value={overview.scoresLive?`${overview.businessHealth} / 100`:"Not enough data"} href="/dashboard/health" detail={overview.scoresLive?overview.businessHealthDeltaLabel:evidenceCoverage!=null?`${evidenceCoverage}% evidence coverage`:"Building evidence"}/>{snapshotPulse.map((kpi)=><PulseCard key={kpi.id} label={kpi.label} value={kpi.value} href={kpi.href}/>)}</div></section>
    {growthScorecard}
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.65fr)_minmax(320px,0.85fr)]"><section className="rounded-2xl border border-slate-800 bg-slate-950/35 p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-emerald-300/80">Business pulse</p><h2 className="mt-1 text-xl font-semibold text-white">Business Health trend</h2><p className="mt-1 text-xs text-slate-500">Persisted measurements only — no synthetic trend data.</p></div><Link href="/dashboard/health" className="text-xs font-medium text-sky-400 hover:underline">Open Health →</Link></div><div className="mt-5"><HealthTrendChart values={overview.healthTrend}/></div></section><section id="todays-priorities" className="rounded-2xl border border-violet-500/20 bg-gradient-to-b from-violet-500/8 to-slate-950/45 p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-violet-300/80">Aida recommends</p><h2 className="mt-1 text-xl font-semibold text-white">Today&apos;s priorities</h2></div><Link href="/dashboard/advisor" className="text-xs text-violet-300 hover:underline">Why these? →</Link></div>{priorityCount?<ol className="mt-5 space-y-4">{overview.priorities.map((priority)=><li key={priority.rank} className="flex gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-violet-400/25 bg-violet-500/10 text-xs font-semibold text-violet-200">{priority.rank}</span><p className="pt-0.5 text-sm leading-6 text-slate-200">{priority.text}</p></li>)}</ol>:<div className="mt-5 rounded-xl border border-slate-800 bg-slate-950/30 p-4"><p className="text-sm font-medium text-white">Nothing urgent is being flagged.</p><p className="mt-1 text-xs leading-5 text-slate-500">Aida will surface priorities here when current business evidence supports them.</p></div>}{overview.prioritiesImpact?<div className="mt-5 rounded-xl border border-emerald-500/15 bg-emerald-500/5 p-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-emerald-300/70">Observed impact</p><p className="mt-1 text-sm text-emerald-100">{overview.prioritiesImpact}</p></div>:null}</section></div>
    {firstInsight?<section className={`rounded-2xl border px-5 py-5 sm:px-6 ${insightTone(firstInsight)}`}><div className="flex flex-wrap items-start justify-between gap-4"><div className="max-w-4xl"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] opacity-60">Aida insight</p><h2 className="mt-2 text-xl font-semibold">{firstInsight.title}</h2><p className="mt-2 text-sm leading-6 opacity-80">{firstInsight.body}</p></div>{firstInsight.href?<Link href={firstInsight.href} className="text-sm font-medium text-sky-300 hover:underline">Open →</Link>:null}</div></section>:null}
    {supportingInsights.length?<section><div className="mb-3"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">Supporting signals</p><h2 className="mt-1 text-lg font-semibold text-white">What else Aida is noticing</h2></div><div className="grid gap-3 lg:grid-cols-3">{supportingInsights.map((insight)=><div key={insight.id} className={`rounded-xl border p-4 ${insightTone(insight)}`}><h3 className="text-sm font-semibold">{insight.title}</h3><p className="mt-2 text-xs leading-5 opacity-75">{insight.body}</p>{insight.href?<Link href={insight.href} className="mt-3 inline-block text-xs font-medium text-sky-300 hover:underline">Open →</Link>:null}</div>)}</div></section>:null}
    <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border border-slate-800 bg-slate-950/35 p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">Goals</p><h2 className="mt-1 text-lg font-semibold text-white">Progress that matters</h2></div><Link href="/dashboard/goals" className="text-xs text-sky-400 hover:underline">Manage goals →</Link></div><div className="mt-4 space-y-3">{overview.goals.length?overview.goals.map((goal)=><GoalRow key={goal.id} goal={goal}/>):<p className="rounded-xl border border-dashed border-slate-800 p-4 text-sm text-slate-500">No active goals yet.</p>}</div></section><section className="rounded-2xl border border-slate-800 bg-slate-950/35 p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-500">Activity</p><h2 className="mt-1 text-lg font-semibold text-white">Recent movement</h2></div><Link href="/dashboard/activity" className="text-xs text-sky-400 hover:underline">View activity →</Link></div><div className="mt-4 space-y-3">{visibleTimeline.length?visibleTimeline.map((item)=><div key={item.id} className="flex items-start gap-3 border-b border-slate-800/70 pb-3 last:border-0 last:pb-0"><StatusDot status={item.status}/><div><p className="text-sm text-slate-200">{item.title}</p><p className="mt-1 text-xs text-slate-500">{item.detail}</p></div></div>):<p className="rounded-xl border border-dashed border-slate-800 p-4 text-sm text-slate-500">No recent activity yet.</p>}</div></section></div>
  </div>;
}
