import type { AppManifest } from "../manifest";

export const crmApp: AppManifest = {
  id: "crm",
  name: "CRM",
  description: "Contacts, companies, and customer relationships",
  tier: "core",
  version: "1.0.0",
  icon: "👤",
  routes: [
    { path: "/apps/crm/contacts", label: "Contacts" },
    { path: "/apps/crm/companies", label: "Companies" },
    { path: "/apps/crm/opportunities", label: "Opportunities" },
    { path: "/apps/crm/pipeline", label: "Pipeline" },
    { path: "/apps/crm/consultations", label: "Consultations" },
    { path: "/apps/crm/tasks", label: "Tasks" },
    { path: "/apps/crm/timeline", label: "Timeline" },
  ],
  navigation: [
    { href: "/apps/crm/contacts", label: "Contacts", icon: "☷" },
    { href: "/apps/crm/companies", label: "Companies", icon: "▣" },
    { href: "/apps/crm/opportunities", label: "Opportunities", icon: "◈" },
    { href: "/apps/crm/pipeline", label: "Pipeline", icon: "⇢" },
    { href: "/apps/crm/consultations", label: "Consultations", icon: "◷" },
    { href: "/apps/crm/tasks", label: "Tasks", icon: "☑" },
    { href: "/apps/crm/timeline", label: "Timeline", icon: "▤" },
  ],
  permissions: [
    { id: "crm.view_contacts", label: "View contacts" },
    { id: "crm.edit_contacts", label: "Edit contacts" },
  ],
  features: [
    "crm.contacts.read",
    "crm.contacts.write",
    "crm.contacts.export",
    "crm.contacts.import",
    "crm.contacts.merge",
    "crm.companies.read",
    "crm.companies.write",
    "crm.leads.read",
    "crm.leads.write",
    "crm.opportunities.read",
    "crm.opportunities.write",
    "crm.tasks.read",
    "crm.tasks.write",
    "crm.timeline.read",
    "crm.tags.write",
  ],
  entities: ["Contact", "Company", "Lead", "Opportunity", "Activity", "Task", "Note"],
  automationTriggers: [
    { id: "contact.created", label: "Contact created", objectType: "Contact" },
    { id: "contact.updated", label: "Contact updated", objectType: "Contact" },
    { id: "opportunity.created", label: "Opportunity created", objectType: "Opportunity" },
    { id: "lead.converted", label: "Lead converted", objectType: "Lead" },
    { id: "task.created", label: "Task created", objectType: "Task" },
    { id: "task.completed", label: "Task completed", objectType: "Task" },
  ],
  automationActions: [
    { id: "contact.assign", label: "Assign contact" },
    { id: "contact.add_tag", label: "Add tag" },
  ],
  aiTools: [
    {
      id: "crm.summarise_contact",
      label: "Summarise contact",
      description: "AI summary of contact history and next actions",
    },
    {
      id: "crm.create_follow_up_task",
      label: "Create follow-up task",
      description:
        "Create an open CRM task from an Advisor recommendation (permission-gated; human approval required)",
    },
  ],
  reports: [{ id: "crm.pipeline_summary", label: "Pipeline summary" }],
};
