import type { AppManifest } from "../manifest";

export const infrastructureApp: AppManifest = {
  id: "infrastructure",
  name: "Infrastructure",
  description:
    "DigitalGate domains, DNS, SSL, hosting, email, backup and Cloudflare status — Core Platform Service",
  tier: "core",
  version: "0.3.0",
  icon: "⚙",
  routes: [
    { path: "/apps/infrastructure/domains", label: "Domains" },
    { path: "/apps/infrastructure/dns", label: "DNS" },
    { path: "/apps/infrastructure/ssl", label: "SSL" },
    { path: "/apps/infrastructure/hosting", label: "Hosting" },
    { path: "/apps/infrastructure/email", label: "Email" },
    { path: "/apps/infrastructure/backup", label: "Backup" },
    { path: "/apps/infrastructure/cloudflare", label: "Cloudflare" },
  ],
  navigation: [
    { href: "/apps/infrastructure/domains", label: "Infrastructure", icon: "⚙" },
  ],
  permissions: [
    { id: "infra.view", label: "View infrastructure" },
    { id: "infra.domains.manage", label: "Manage domains" },
    { id: "infra.dns.manage", label: "Manage DNS" },
    { id: "infra.email.manage", label: "Manage email infrastructure" },
    { id: "infra.hosting.manage", label: "Manage hosting" },
    { id: "infra.backups.manage", label: "Export backups" },
    { id: "infra.deploy", label: "Deploy sites" },
  ],
  features: [
    "infra.domains.read",
    "infra.domains.register",
    "infra.dns.read",
    "infra.dns.write",
    "infra.ssl.read",
    "infra.email.read",
    "infra.email.send",
    "infra.hosting.read",
    "infra.hosting.provision",
    "infra.deploy.staging",
    "infra.deploy.production",
    "infra.monitoring.read",
    "infra.backups.read",
  ],
  entities: ["Document", "Activity"],
  automationTriggers: [],
  automationActions: [],
  aiTools: [],
  reports: [],
};
