import { redirectUnlessStaffNetwork, PlatformHubPage } from "@/lib/network-staff-gate";

export default async function NetworkCommissionsPage() {
  await redirectUnlessStaffNetwork("/dashboard/network/refer-earn");

  return (
    <PlatformHubPage
      title="Commissions"
      description="Financial obligations generated by the DigitalGate commercial network — calculation, attribution, approval, payment and history. Partner relationships live under DigitalGate → Partners."
      links={[
        {
          href: "/command/commissions",
          label: "Commission queue",
          detail: "Pending · approved · paid.",
        },
        {
          href: "/command/partners/payouts",
          label: "Payouts",
          detail: "Payout runs and status.",
        },
        {
          href: "/command/partners",
          label: "Partners dashboard",
          detail: "Who earned them — relationship management.",
        },
      ]}
    />
  );
}
