"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ResolutionFallback } from "@/components/ui/ResolutionAction";

type DisplayState = "connected" | "attention" | "not_connected" | "available" | "planned";
type Connector = { manifest:{ id:string; name:string; category:"property"|"business"|"marketing"|"commerce"|"ops"; maturity:"native"|"available"|"planned"; capabilities:string[] }; platformConfigured:boolean; connectionScope:"platform"|"organisation"; organisation?:{ status?:string; label?:string|null; lastError?:string|null; lastSyncAt?:string|null }; health?:{ status?:string; lastError?:string|null; lastSyncAt?:string|null } };
const STATUS:Record<DisplayState,{label:string;className:string}>={connected:{label:"● Connected",className:"text-emerald-400"},attention:{label:"● Needs attention",className:"text-amber-300"},not_connected:{label:"● Not connected",className:"text-red-300"},available:{label:"○ Available",className:"text-slate-300"},planned:{label:"○ Planned",className:"text-slate-500"}};
const CATEGORY={ops:"Communications & operations",business:"Business presence",marketing:"Marketing & social",commerce:"Finance & commerce",property:"Property"} as const;
const ACTIONS:Record<string,{href:string;connectedHref?:string;label?:string}>={"google-gmail":{href:"/api/connectors/google-gmail/connect",connectedHref:"/apps/communications/mailboxes"},"google-gbp":{href:"/api/connectors/google/connect?returnTo=/dashboard/settings/connected-services"},"microsoft-365":{href:"/api/connectors/microsoft-365/connect",connectedHref:"/apps/communications/mailboxes"},"apple-icloud":{href:"/apps/communications/mailboxes",connectedHref:"/apps/communications/mailboxes"},linkedin:{href:"/api/connectors/linkedin/connect"},wordpress:{href:"/dashboard/settings/connectors",label:"Advanced"},rea:{href:"/dashboard/settings/connectors",label:"Advanced"},domain:{href:"/dashboard/settings/connectors",label:"Advanced"}};
function displayState(c:Connector):DisplayState{if(c.manifest.maturity==="planned")return"planned";const s=c.organisation?.status;if(s==="connected"){if(c.organisation?.lastError||c.health?.lastError||c.health?.status==="degraded"||c.health?.status==="error")return"attention";return"connected"}if(s==="pending_auth"||s==="degraded"||s==="error")return"attention";if(c.manifest.maturity==="available"||!c.platformConfigured)return"available";return"not_connected"}
function ServiceCard({connector:c}:{connector:Connector}){const state=displayState(c),status=STATUS[state],action=ACTIONS[c.manifest.id],href=state==="connected"&&action?.connectedHref?action.connectedHref:action?.href,lastSync=c.organisation?.lastSyncAt??c.health?.lastSyncAt;return <li className="rounded-xl border border-slate-700/70 bg-slate-950/40 px-4 py-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 max-w-xl"><p className="font-medium text-white">{c.manifest.name}</p><p className={`mt-2 text-xs ${status.className}`}>{status.label}</p>{c.organisation?.label?<p className="mt-1 text-xs text-slate-500">{c.organisation.label}</p>:null}{lastSync?<p className="mt-1 text-xs text-slate-500">Last synced {new Date(lastSync).toLocaleString("en-AU")}</p>:null}{c.organisation?.lastError||c.health?.lastError?<p className="mt-1 text-xs text-amber-300">{c.organisation?.lastError??c.health?.lastError}</p>:null}{c.manifest.capabilities.length?<p className="mt-2 text-xs text-slate-500">Enables: {c.manifest.capabilities.join(" · ")}</p>:null}{state==="planned"?<p className="mt-1 text-xs text-slate-500">On the DigitalGate roadmap — not currently presented as operational.</p>:null}{state==="available"?<p className="mt-1 text-xs text-slate-500">Optional supported integration. It is not required for this organisation.</p>:null}</div>{href&&state!=="planned"?(href.startsWith("/api/")?<a href={href} className="rounded-full bg-sky-600 px-4 py-1.5 text-xs font-semibold text-white hover:bg-sky-500">{action?.label??(state==="connected"?"Manage":"Connect")}</a>:<Link href={href} className="rounded-full bg-sky-600 px-4 py-1.5 text-xs font-semibold text-white hover:bg-sky-500">{action?.label??(state==="connected"?"Manage":"Connect")}</Link>):null}</div></li>}
export function ConnectedServicesCatalog(){const[connectors,setConnectors]=useState<Connector[]|null>(null),[error,setError]=useState<string|null>(null),[reloadKey,setReloadKey]=useState(0);useEffect(()=>{let cancelled=false;async function load(){setError(null);try{const response=await fetch("/api/v1/connectors",{cache:"no-store"});if(!response.ok)throw new Error("catalogue_unavailable");const json=await response.json();const items:Connector[]=(json?.data?.connectors??[]).filter((item:Connector)=>item.connectionScope==="organisation");if(!cancelled)setConnectors(items)}catch{if(!cancelled)setError("DigitalGate could not refresh your connection status.")}}void load();return()=>{cancelled=true}},[reloadKey]);const groups=useMemo(()=>{if(!connectors)return null;return(Object.keys(CATEGORY)as Array<keyof typeof CATEGORY>).map(category=>({category,title:CATEGORY[category],connectors:connectors.filter(item=>item.manifest.category===category)})).filter(group=>group.connectors.length)},[connectors]);if(error)return <div className="rounded-xl border border-amber-400/25 bg-amber-400/5 p-5"><p className="font-medium text-amber-200">Connection status needs another check</p><p className="mt-1 text-sm text-slate-400">{error}</p><button type="button" onClick={()=>setReloadKey(v=>v+1)} className="mt-3 rounded-full bg-sky-600 px-4 py-2 text-xs font-semibold text-white">Retry</button><ResolutionFallback /></div>;if(!groups)return <p className="text-sm text-slate-500">Loading connected services…</p>;return <section className="space-y-6"><div><h2 className="text-lg font-semibold text-white">Services for this organisation</h2><p className="mt-1 text-sm text-slate-400">Operational truth comes from the Connector Engine. Planned services remain separate from integrations that can be connected today.</p></div>{groups.map(group=><section key={group.category} className="space-y-3"><h3 className="text-sm font-semibold uppercase tracking-[0.12em] text-slate-400">{group.title}</h3><ul className="space-y-3">{group.connectors.map(c=><ServiceCard key={c.manifest.id} connector={c}/>)}</ul></section>)}</section>}
