"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type LinkedInOrg = { urn:string; role?:string; state?:string; name?:string; vanityName?:string };
type LinkedInStatus = { platform:{ configured:boolean; clientIdSet:boolean; secretSet:boolean; redirectUri:string }; organisation:{ id:string; name:string; connected:boolean; expiresAt:string|null; connectedAt:string|null; scope:string|null; label:string|null; member:{name?:string;email?:string}|null; organizations:LinkedInOrg[]; selectedOrganizationUrn:string|null; lastError:string|null; probe:{ok:boolean;connected:boolean;apiOk?:boolean;message:string}|null } };

export function LinkedInConnectorPanel({ flash, flashMessage }: { flash?:"connected"|"attention"|"error"|null; flashMessage?:string|null }) {
  const [status,setStatus]=useState<LinkedInStatus|null>(null); const [error,setError]=useState<string|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [selectedOrg,setSelectedOrg]=useState<string>("");
  async function load(){setLoading(true);setError(null);const res=await fetch("/api/v1/connectors/linkedin/status");const json=await res.json().catch(()=>({}));setLoading(false);if(!res.ok){setError(json.error?.message??"Could not load LinkedIn status");return}setStatus(json.data as LinkedInStatus);setSelectedOrg(json.data.organisation.selectedOrganizationUrn??"")}
  async function saveSelection(){setBusy(true);setError(null);const res=await fetch("/api/v1/connectors/linkedin/selection",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organizationUrn:selectedOrg})});const json=await res.json().catch(()=>({}));setBusy(false);if(!res.ok){setError(json.error?.message??"Could not save LinkedIn company selection");return}await load()}\n  async function disconnect(){setBusy(true);setError(null);const res=await fetch("/api/v1/connectors/linkedin/disconnect",{method:"POST"});const json=await res.json().catch(()=>({}));setBusy(false);if(!res.ok){setError(json.error?.message??"Could not disconnect LinkedIn");return}await load()}
  useEffect(()=>{void load()},[]);
  const platform=status?.platform,org=status?.organisation,pages=org?.organizations??[];
  return <div className="dg-card"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-wide text-slate-500">Social</p><h2 className="font-semibold text-white">LinkedIn</h2><p className="mt-1 text-sm text-slate-400">Connect the DigitalGate company page. Compose still saves drafts — posting to LinkedIn is the next slice.</p></div><div className="flex flex-wrap gap-2">{org?.connected?<button type="button" disabled={busy} onClick={()=>void disconnect()} className="rounded-full border border-slate-600 px-4 py-1.5 text-xs font-semibold text-slate-200 hover:border-red-500/60 hover:text-red-300 disabled:opacity-50">Disconnect</button>:null}<a href="/api/connectors/linkedin/connect" className={`rounded-full px-4 py-1.5 text-xs font-semibold text-white ${platform?.configured?"bg-blue-600 hover:bg-blue-500":"pointer-events-none bg-slate-700 text-slate-400"}`}>{org?.connected?"Reconnect":"Connect LinkedIn"}</a></div></div>
  {flash==="connected"?<p className="mt-3 text-sm text-emerald-400">LinkedIn connected. Company pages appear below when Community Management API access is granted.</p>:null}
  {flash==="attention"?<p className="mt-3 text-sm text-amber-400">LinkedIn authorised, but the connection needs attention{flashMessage?`: ${flashMessage}`:"."}</p>:null}
  {flash==="error"?<p className="mt-3 text-sm text-red-300">LinkedIn connect failed{flashMessage?`: ${flashMessage}`:" — try again."}</p>:null}
  {error?<p className="mt-3 text-sm text-amber-400">{error}</p>:null}{loading&&!status?<p className="mt-3 text-sm text-slate-500">Checking…</p>:null}
  {platform?<ul className="mt-4 space-y-2 text-sm text-slate-400"><li>Platform credentials: <span className={platform.configured?"text-emerald-400":"text-amber-400"}>{platform.configured?"Configured":"Missing LINKEDIN_CLIENT_ID / LINKEDIN_CLIENT_SECRET"}</span></li><li className="font-mono text-xs text-slate-500">Redirect: {platform.redirectUri}</li>{org?<><li>Org ({org.name}): <span className={org.connected?"text-emerald-400":"text-slate-500"}>{org.connected?`Connected${org.connectedAt?` · ${new Date(org.connectedAt).toLocaleString("en-AU")}`:""}`:"Not connected"}</span></li>{org.member?.name||org.member?.email?<li>Signed in as <span className="text-slate-300">{org.member.name||org.member.email}</span></li>:null}{org.probe?<li>Probe: <span className={org.probe.ok?"text-emerald-400":"text-amber-400"}>{org.probe.message}</span></li>:null}{org.lastError?<li>Last issue: <span className="text-amber-300">{org.lastError}</span></li>:null}</>:null}</ul>:null}
  {pages.length?<div className="mt-5 border-t border-slate-800 pt-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Company pages</p><p className="mt-1 text-xs text-slate-500">Choose the LinkedIn company page that belongs to this organisation.</p><div className="mt-2 space-y-2">{pages.map(page=><label key={page.urn} className="flex cursor-pointer items-start gap-3 rounded-lg border border-slate-800 bg-slate-950/40 px-3 py-3 text-sm text-slate-300"><input type="radio" name="linkedin-company" checked={selectedOrg===page.urn} onChange={()=>setSelectedOrg(page.urn)} className="mt-1"/><span><span className="font-medium text-white">{page.name||page.vanityName||page.urn}</span>{page.role?<span className="ml-2 text-xs text-slate-500">{page.role}</span>:null}</span></label>)}</div><button type="button" disabled={busy||!selectedOrg} onClick={()=>void saveSelection()} className="mt-3 rounded-full bg-blue-600 px-4 py-1.5 text-xs font-semibold text-white disabled:opacity-50">Save organisation selection</button></div>:null}
  <p className="mt-4 text-xs text-slate-500">Need to change the public LinkedIn URL instead? <Link href="/dashboard/business" className="text-blue-400 hover:underline">Edit Business Profile</Link>.</p></div>;
}
