/**
 * Partner Commissions workspace — financial ledger for the Partner Network.
 *
 * Developer rule: Commissions consume referral and revenue attribution data.
 * This is not a manual commission calculator — entries should be generated from
 * qualifying Stripe/billing revenue where possible.
 *
 * Separation: Sales acquires · Referrals attribute · Commissions calculate · Revenue records.
 */

import { listAllCommissions } from "./crud";
import {
  BPS,
  COMMISSION_PERIOD_MONTHS,
  COMMERCIAL_MODEL_SUMMARY,
  bpsToPercentLabel,
} from "./commercial-model";
import type { CommissionStatus, SerializedPartnerCommission } from "./types";

export const COMMISSION_LIFECYCLE_STRIP =
  "Generated → Pending → Approved → Payable → Paid";

export const COMMISSION_LIFECYCLE_STAGES = [
  {
    id: "generated",
    label: "Generated",
    rule: "Revenue has been recorded and a commission calculation exists.",
  },
  {
    id: "pending",
    label: "Pending",
    rule: "Revenue is subject to the applicable payment and retention conditions.",
  },
  {
    id: "approved",
    label: "Approved",
    rule: "Commission has been reviewed and approved.",
  },
  {
    id: "payable",
    label: "Payable",
    rule: "Commission is eligible for payment in the next payment run.",
  },
  {
    id: "paid",
    label: "Paid",
    rule: "Payment has been made and recorded.",
  },
] as const;

export const COMMISSION_MODEL_SECTIONS = [
  {
    title: "Acquisition Partners",
    body: `${bpsToPercentLabel(BPS.RESELLER)} of qualifying Platform + App subscription revenue for the first ${COMMISSION_PERIOD_MONTHS} months of each directly acquired customer.`,
  },
  {
    title: "Acquisition Channel Managers",
    body: `${bpsToPercentLabel(BPS.CHANNEL_MANAGER_DIRECT)} on their own directly acquired customers. Plus ${bpsToPercentLabel(BPS.CHANNEL_MANAGER_OVERRIDE)} override on qualifying Platform + App revenue generated by Acquisition Partners they directly manage, for the first ${COMMISSION_PERIOD_MONTHS} months of those customers.`,
    note: "The override is additive — not a reduction in the Acquisition Partner's 25%. Example split: Acquisition Partner 25% · Channel Manager 5% override · DigitalGate 70%.",
  },
  {
    title: "Delivery Partners",
    body: `${bpsToPercentLabel(BPS.DELIVERY_PARTNER)} of qualifying Professional Services + Support & Success revenue attributable to their delivery work. No Platform subscription commission.`,
  },
  {
    title: "Delivery Channel Managers",
    body: `${bpsToPercentLabel(BPS.DELIVERY_CHANNEL_MANAGER_DIRECT)} on their own delivery revenue. Plus ${bpsToPercentLabel(BPS.DELIVERY_CHANNEL_MANAGER_OVERRIDE)} override on qualifying service revenue generated by Delivery Partners they directly manage.`,
  },
  {
    title: "Founding Referral Programmes",
    body: `Separate from Acquisition Partner status — Founding 10: ${bpsToPercentLabel(BPS.FOUNDING_10_REFERRAL)} · Founding 100: ${bpsToPercentLabel(BPS.FOUNDING_100_REFERRAL)} · Founding 1,000+: ${bpsToPercentLabel(BPS.FOUNDING_1000_REFERRAL)}. All based on qualifying Platform + App revenue for the first ${COMMISSION_PERIOD_MONTHS} months.`,
  },
] as const;

export const COMMISSION_ARCHITECTURE_NOTE =
  "Sales acquires DigitalGate customers. Partners extend acquisition and delivery capacity. Referrals attribute where customers came from. Commissions calculate what partners earn. Revenue records what DigitalGate actually receives.";

export type CommissionPulse = {
  totalEarnedCents: number;
  pendingCents: number;
  approvedCents: number;
  payableCents: number;
  paidCents: number;
  thisMonthCents: number;
};

export type CommissionLedgerRow = {
  id: string;
  partnerId: string;
  partnerName: string | null;
  typeLabel: string;
  customerLabel: string;
  revenueLabel: string;
  rateLabel: string;
  periodLabel: string;
  commissionLabel: string;
  statusLabel: string;
  status: CommissionStatus;
  auditLines: string[];
};

export type CommissionsWorkspace = {
  pulse: CommissionPulse;
  lifecycleCounts: Array<{ id: string; label: string; count: number }>;
  rows: CommissionLedgerRow[];
  total: number;
  /** Raw rows for admin status actions */
  commissions: SerializedPartnerCommission[];
};

function formatAud(cents: number, decimals = 2) {
  return (cents / 100).toLocaleString("en-AU", {
    style: "currency",
    currency: "AUD",
    maximumFractionDigits: decimals,
    minimumFractionDigits: decimals,
  });
}

function monthStartUtc(): Date {
  const d = new Date();
  return new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), 1, 0, 0, 0));
}

function lifecycleBucket(status: CommissionStatus): string {
  const s = status.toLowerCase();
  if (s === "calculated" || s === "earned" || s === "generated") return "generated";
  if (s === "pending") return "pending";
  if (s === "approved") return "approved";
  if (s === "payable") return "payable";
  if (s === "paid") return "paid";
  return "pending";
}

function statusDisplayLabel(status: CommissionStatus): string {
  const bucket = lifecycleBucket(status);
  const match = COMMISSION_LIFECYCLE_STAGES.find((stage) => stage.id === bucket);
  return match?.label ?? status;
}

function typeLabel(c: SerializedPartnerCommission): string {
  if (c.commissionKind === "override") return "Channel override";
  if (c.revenueType === "professional_services") return "Delivery Partner";
  if (c.revenueType === "support_success") return "Delivery Partner · Support";
  return "Acquisition Partner";
}

function revenueTypeLabel(c: SerializedPartnerCommission): string {
  switch (c.revenueType) {
    case "platform_subscription":
      return "Platform + Apps";
    case "industry_app_subscription":
      return "Industry Apps";
    case "growth_app_subscription":
      return "Growth Apps";
    case "professional_services":
      return "Professional Services";
    case "support_success":
      return "Support & Success";
    default:
      return "Qualifying revenue";
  }
}

function periodLabel(c: SerializedPartnerCommission): string {
  if (!c.periodStart) return "—";
  const start = new Date(c.periodStart).toLocaleDateString("en-AU", {
    month: "short",
    year: "numeric",
  });
  if (!c.periodEnd) return start;
  const end = new Date(c.periodEnd).toLocaleDateString("en-AU", {
    month: "short",
    year: "numeric",
  });
  return `${start} – ${end}`;
}

function auditLines(c: SerializedPartnerCommission): string[] {
  const lines = [
    c.partnerName ? `${c.partnerName}` : "Partner",
    c.businessName ? `Customer: ${c.businessName}` : null,
    `${revenueTypeLabel(c)}: ${formatAud(c.qualifyingRevenueCents)}`,
    `${typeLabel(c)}: ${c.commissionPercent}%`,
    `Commission: ${formatAud(c.commissionAmountCents)}`,
    c.commissionKind === "override" && c.sourcePartnerId
      ? `Originating partner record: ${c.sourcePartnerId.slice(0, 8)}…`
      : null,
    `Referral: ${c.referralId.slice(0, 8).toUpperCase()}`,
    `Generated: ${new Date(c.createdAt).toLocaleDateString("en-AU")}`,
    `Status: ${statusDisplayLabel(c.status)}`,
    `Revenue source: Stripe (scaffold)`,
  ].filter(Boolean) as string[];
  return lines;
}

function sumByStatus(
  commissions: SerializedPartnerCommission[],
  statuses: Set<string>,
): number {
  return commissions
    .filter((c) => statuses.has(c.status.toLowerCase()))
    .reduce((sum, c) => sum + c.commissionAmountCents, 0);
}

export async function buildCommissionsWorkspace(): Promise<CommissionsWorkspace> {
  let commissions: SerializedPartnerCommission[] = [];
  let total = 0;

  try {
    const result = await listAllCommissions({ limit: 500 });
    commissions = result.commissions;
    total = result.total;
  } catch {
    /* tables not migrated */
  }

  const active = commissions.filter(
    (c) => !["reversed", "cancelled"].includes(c.status.toLowerCase()),
  );
  const monthStart = monthStartUtc();
  const thisMonthCents = active
    .filter((c) => new Date(c.createdAt) >= monthStart)
    .reduce((sum, c) => sum + c.commissionAmountCents, 0);

  const pulse: CommissionPulse = {
    totalEarnedCents: active.reduce((sum, c) => sum + c.commissionAmountCents, 0),
    pendingCents: sumByStatus(active, new Set(["calculated", "pending", "earned"])),
    approvedCents: sumByStatus(active, new Set(["approved"])),
    payableCents: sumByStatus(active, new Set(["payable"])),
    paidCents: sumByStatus(active, new Set(["paid"])),
    thisMonthCents,
  };

  const lifecycleCounts = COMMISSION_LIFECYCLE_STAGES.map((stage) => ({
    id: stage.id,
    label: stage.label,
    count: active.filter((c) => lifecycleBucket(c.status) === stage.id).length,
  }));

  const rows: CommissionLedgerRow[] = commissions.map((c) => ({
    id: c.id,
    partnerId: c.partnerId,
    partnerName: c.partnerName,
    typeLabel: typeLabel(c),
    customerLabel: c.businessName ?? "—",
    revenueLabel: formatAud(c.qualifyingRevenueCents),
    rateLabel: `${c.commissionPercent}%`,
    periodLabel: periodLabel(c),
    commissionLabel: formatAud(c.commissionAmountCents),
    statusLabel: statusDisplayLabel(c.status),
    status: c.status,
    auditLines: auditLines(c),
  }));

  return {
    pulse,
    lifecycleCounts,
    rows,
    total,
    commissions,
  };
}

/** Re-export summary for docs parity */
export { COMMERCIAL_MODEL_SUMMARY };
