import { discoverOrgGoogleAnalyticsProperties, discoverOrgGoogleSearchConsoleSites, getOrgGoogleAnalyticsSettings } from "@dg/platform-core";
import Link from "next/link";
import { getPlatformPageContext } from "@/lib/platform-page-context";
export const dynamic = "force-dynamic";

function friendlyGoogleError(message: string) {
  if (/insufficient authentication scopes|insufficient permission|ACCESS_TOKEN_SCOPE_INSUFFICIENT/i.test(message)) {
    return "The current Google connection does not include permission for this data source. Re-authorise Google above to grant Analytics and Search Console read access.";
  }
  return message.length > 280 ? "Google could not load this data source. Re-authorise the connection or try again shortly." : message;
}

export default async function GoogleAnalyticsConnectorPage() {
  const { session } = await getPlatformPageContext(); const organisationId = session?.organisationId;
  if (!organisationId) return <main className="dg-page-main"><section className="dg-card">Select an organisation to configure Google.</section></main>;
  const [settings, analytics, search] = await Promise.all([getOrgGoogleAnalyticsSettings(organisationId), discoverOrgGoogleAnalyticsProperties(organisationId), discoverOrgGoogleSearchConsoleSites(organisationId)]);
  return <main className="dg-page-main space-y-6"><section className="dg-card"><div className="flex items-start justify-between gap-4"><div><h1 className="text-xl font-semibold text-white">Google Analytics & Search Console</h1><p className="mt-1 text-sm text-slate-400">Choose the Google properties DigitalGate should use as evidence for Analytics, your Digital Twin and Aida.</p></div><Link href="/apps/analytics/connectors" className="text-sm text-sky-400 hover:underline">Back to data sources</Link></div>{(!analytics.ok&&!search.ok)?<div className="mt-5 rounded-lg border border-amber-700/50 bg-amber-950/20 p-4 text-sm text-amber-100"><p>The current Google connection needs Analytics and Search Console read access.</p><Link href="/api/connectors/google/connect?returnTo=/apps/analytics/connectors/google" className="mt-2 inline-block text-sky-400 hover:underline">Re-authorise Google →</Link></div>:null}</section>
  <section className="dg-card"><h2 className="font-semibold text-white">Google Analytics 4</h2><p className="mt-1 text-sm text-slate-400">{settings.propertyLabel?`Selected: ${settings.propertyLabel}`:"No property selected yet."}</p>{analytics.ok?<div className="mt-4 space-y-2">{analytics.properties.map((p)=><form key={p.name} action="/api/v1/connectors/google/analytics/config" method="post" className="flex items-center justify-between gap-3 rounded-lg border border-slate-700 p-3"><input type="hidden" name="property" value={p.name}/><input type="hidden" name="propertyLabel" value={p.displayName}/><div><div className="text-sm font-medium text-white">{p.displayName}</div><div className="text-xs text-slate-500">{p.name}</div></div>{settings.property===p.name?<span className="text-sm text-emerald-400">Selected</span>:<button type="submit" className="rounded-md border border-sky-700 px-3 py-1.5 text-sm text-sky-300 hover:bg-sky-950/40">Use property</button>}</form>)}</div>:<p className="mt-3 text-sm text-amber-300">{friendlyGoogleError(analytics.message)}</p>}</section>
  <section className="dg-card"><h2 className="font-semibold text-white">Google Search Console</h2><p className="mt-1 text-sm text-slate-400">{settings.searchConsoleSite?`Selected: ${settings.searchConsoleSite}`:"No site selected yet."}</p>{search.ok?<div className="mt-4 space-y-2">{search.sites.map((site)=><form key={site.siteUrl} action="/api/v1/connectors/google/analytics/config" method="post" className="flex items-center justify-between gap-3 rounded-lg border border-slate-700 p-3"><input type="hidden" name="searchConsoleSite" value={site.siteUrl}/><div><div className="text-sm font-medium text-white">{site.siteUrl}</div><div className="text-xs text-slate-500">{site.permissionLevel||"Google property"}</div></div>{settings.searchConsoleSite===site.siteUrl?<span className="text-sm text-emerald-400">Selected</span>:<button type="submit" className="rounded-md border border-sky-700 px-3 py-1.5 text-sm text-sky-300 hover:bg-sky-950/40">Use site</button>}</form>)}</div>:<p className="mt-3 text-sm text-amber-300">{friendlyGoogleError(search.message)}</p>}</section></main>;
}
