/**
 * DigitalGate Insights — editorial catalog, relationships and audit metadata.
 * SoT for internal linking, related content and product connections.
 */
export const SITE = "https://digitalgate.com.au";

export const AUTHOR = {
  name: "Ben Roe",
  role: "Founder & Platform Architect, DigitalGate",
  bio: "Ben Roe builds DigitalGate — the Business Operating Platform for connected, intelligent businesses. These Insights explain the philosophy behind the product.",
};

export const ARCHITECTURE = {
  core: { id: "core", label: "Core", verbs: ["connected business", "CRM", "communications", "documents", "commerce"] },
  industry: { id: "industry", label: "Industry", verbs: ["real estate", "accommodation", "services", "finance"] },
  growth: { id: "growth", label: "Growth", verbs: ["SEO", "AI Visibility", "automation", "analytics", "social", "reputation", "prospecting"] },
  intelligence: { id: "intelligence", label: "Intelligence", verbs: ["Digital Twin", "Business Brain", "AI Advisor", "Business Health"] },
};

/** @typedef {'keep'|'expand'|'rewrite'|'consolidate'|'redirect'|'migrate'} InsightAction */

export const INSIGHTS = [
  {
    id: "foundational-1",
    slug: "from-dumb-businesses-to-smart-businesses",
    url: "/from-dumb-businesses-to-smart-businesses/",
    title: "From fragmented businesses to intelligent ones",
    seoTitle: "From Dumb Businesses to Smart Businesses | DigitalGate Insights",
    status: "published",
    source: "gen2",
    pillar: true,
    primaryTopic: "intelligence",
    secondaryTopics: ["core", "growth"],
    category: "Connected Business",
    searchIntent: "informational",
    primaryKeyword: "connected business",
    secondaryKeywords: ["business operating platform", "AI business context", "intelligent business"],
    audience: ["SME", "founders", "operators"],
    wordCount: 1608,
    internalLinks: 8,
    published: "2026-08-01",
    updated: "2026-08-27",
    readMinutes: 8,
    productHref: "/",
    productLabel: "Explore the Business Operating Platform",
    productBlurb: "Core, Industry, Growth and Intelligence on one connected foundation.",
    thin: false,
    score: 88,
    action: "expand",
    actionNotes: "Add author/trust layer, Related Insights, Explore block, FAQ schema, links to /growth and /business-brain.",
    seoIssues: ["Missing canonical link tag", "No FAQPage schema despite pillar status"],
    aiIssues: ["Strong definitions in body — add explicit definition block for Connected Business"],
    uxIssues: ["No published/updated meta row", "No Continue exploring footer"],
    recommendation: "expand",
    related: ["foundational-2", "business-brain", "ai-search-vs-seo"],
  },
  {
    id: "foundational-2",
    slug: "intelligent-business-more-than-a-brain",
    url: "/intelligent-business-more-than-a-brain/",
    title: "The intelligent business is more than a brain",
    seoTitle: "The Intelligent Business Is More Than a Brain | DigitalGate Insights",
    status: "published",
    source: "gen2",
    pillar: true,
    primaryTopic: "intelligence",
    secondaryTopics: ["core"],
    category: "Business Operating System",
    searchIntent: "informational",
    primaryKeyword: "intelligent business",
    secondaryKeywords: ["business operating system", "connected business architecture"],
    audience: ["SME", "founders", "technical leaders"],
    wordCount: 1370,
    internalLinks: 7,
    published: "2026-08-20",
    updated: "2026-08-27",
    readMinutes: 7,
    productHref: "/business-brain/",
    productLabel: "Business Brain™",
    productBlurb: "The intelligence layer that combines context, knowledge and live signals.",
    thin: false,
    score: 86,
    action: "expand",
    actionNotes: "Add author, related insights, FAQ on Business Brain vs chatbot.",
    seoIssues: ["Missing canonical"],
    aiIssues: ["Body map is excellent — add standalone Digital Twin definition block"],
    uxIssues: ["No editorial footer components"],
    recommendation: "expand",
    related: ["foundational-1", "business-brain", "ai-visibility-framework"],
  },
  {
    id: "business-brain",
    slug: "business-brain",
    url: "/business-brain/",
    title: "Business Brain™",
    seoTitle: "Business Brain™ | DigitalGate",
    status: "published",
    source: "gen2",
    pillar: true,
    primaryTopic: "intelligence",
    secondaryTopics: ["core", "growth"],
    category: "Intelligence",
    searchIntent: "informational",
    primaryKeyword: "business brain",
    secondaryKeywords: ["business intelligence platform", "AI business context", "digital twin"],
    audience: ["SME", "founders"],
    wordCount: 478,
    internalLinks: 8,
    published: "2026-06-01",
    updated: "2026-08-27",
    readMinutes: 3,
    productHref: "https://app.digitalgate.com.au",
    productLabel: "Explore DigitalGate",
    productBlurb: "See Business Brain, Digital Twin and AI Advisor in the platform.",
    thin: true,
    score: 52,
    action: "rewrite",
    actionNotes: "Pillar destination too thin — expand with definition, FAQ, how it differs from CRM/chatbot, honest capability scope.",
    seoIssues: ["Meta description product-led not search-intent", "H1 marketing not definitional"],
    aiIssues: ["No clear 'What is Business Brain' definition sentence for LLMs"],
    uxIssues: ["No author, related insights, or sticky nav for pillar depth"],
    recommendation: "rewrite",
    related: ["foundational-1", "foundational-2", "ai-search-vs-seo"],
  },
  {
    id: "ai-visibility-framework",
    slug: "ai-visibility-framework",
    url: "/ai-visibility-framework/",
    title: "AI Visibility Framework™",
    seoTitle: "AI Visibility Framework™ | DigitalGate",
    status: "published",
    source: "gen2",
    pillar: true,
    primaryTopic: "growth",
    secondaryTopics: ["industry"],
    category: "AI Visibility · Real Estate",
    searchIntent: "informational",
    primaryKeyword: "AI visibility framework",
    secondaryKeywords: ["AI search optimisation", "entity SEO", "real estate AI visibility"],
    audience: ["real estate agencies"],
    wordCount: 1058,
    internalLinks: 11,
    published: "2026-05-01",
    updated: null,
    readMinutes: 5,
    productHref: "/ai-visibility/",
    productLabel: "DigitalGate AI Visibility",
    productBlurb: "AI Visibility Score, readiness signals and connection to SEO on-platform.",
    thin: false,
    score: 74,
    action: "expand",
    actionNotes: "Add to insights index; link to /ai-visibility; add author; clarify no live citation monitoring.",
    seoIssues: ["Not linked from /insights/", "Full HTML document wrapper may duplicate chrome"],
    aiIssues: ["Good methodology — add explicit 'What is AI Visibility' definition block"],
    uxIssues: ["Different template from foundational series", "Missing from topic clusters"],
    recommendation: "expand",
    related: ["ai-search-vs-seo", "ai-visibility-re", "chatgpt-recommends"],
  },
  {
    id: "appraisal-magnet",
    slug: "appraisal-magnet-system",
    url: "/appraisal-magnet-system/",
    title: "Appraisal Magnet System™",
    status: "published",
    source: "gen2",
    pillar: false,
    primaryTopic: "industry",
    secondaryTopics: ["growth"],
    category: "Real Estate · Lead Generation",
    searchIntent: "commercial",
    primaryKeyword: "real estate vendor leads",
    audience: ["real estate agencies"],
    wordCount: 1020,
    internalLinks: 10,
    productHref: "/apps/industry/property/",
    productLabel: "DigitalGate for Property",
    thin: false,
    score: 71,
    action: "expand",
    recommendation: "expand",
    related: ["listing-pipeline", "vendor-velocity", "local-seo-vendor-leads"],
  },
  {
    id: "listing-pipeline",
    slug: "listing-pipeline-framework",
    url: "/listing-pipeline-framework/",
    title: "Listing Pipeline Framework™",
    status: "published",
    source: "gen2",
    pillar: false,
    primaryTopic: "industry",
    category: "Real Estate · Operations",
    wordCount: 960,
    internalLinks: 13,
    productHref: "/apps/industry/property/",
    thin: false,
    score: 70,
    action: "expand",
    recommendation: "expand",
    related: ["appraisal-magnet", "vendor-velocity"],
  },
  {
    id: "vendor-velocity",
    slug: "vendor-velocity-system",
    url: "/vendor-velocity-system/",
    title: "Vendor Velocity System™",
    status: "published",
    source: "gen2",
    pillar: false,
    primaryTopic: "industry",
    category: "Real Estate · Operations",
    wordCount: 735,
    internalLinks: 10,
    thin: true,
    score: 64,
    action: "expand",
    recommendation: "expand",
    related: ["listing-pipeline", "appraisal-magnet"],
  },
  {
    id: "chatgpt-recommends",
    slug: "how-chatgpt-chooses-which-businesses-to-recommend",
    url: "/how-chatgpt-chooses-which-businesses-to-recommend",
    title: "How ChatGPT Chooses Which Businesses To Recommend in 2026",
    status: "published",
    source: "wordpress",
    pillar: true,
    primaryTopic: "growth",
    secondaryTopics: ["industry"],
    category: "AI Visibility",
    searchIntent: "informational",
    primaryKeyword: "ChatGPT business recommendations",
    audience: ["SME", "real estate", "services"],
    wordCount: 1200,
    internalLinks: 2,
    productHref: "/ai-visibility/",
    productLabel: "DigitalGate AI Visibility",
    thin: false,
    score: 72,
    action: "migrate",
    actionNotes: "Migrate to Gen 2 SoT with shared editorial template; add internal links.",
    recommendation: "migrate",
    related: ["ai-search-vs-seo", "gemini-local", "will-ai-replace-google"],
  },
  {
    id: "gemini-local",
    slug: "how-gemini-recommends-local-businesses",
    url: "/how-gemini-recommends-local-businesses",
    title: "How Gemini Recommends Local Businesses and Service Providers",
    status: "published",
    source: "wordpress",
    primaryTopic: "growth",
    category: "AI Visibility",
    wordCount: 1100,
    internalLinks: 2,
    productHref: "/ai-visibility/",
    score: 70,
    action: "migrate",
    recommendation: "migrate",
    related: ["chatgpt-recommends", "local-seo-ai-age"],
  },
  {
    id: "will-ai-replace-google",
    slug: "will-ai-replace-google-search",
    url: "/will-ai-replace-google-search",
    title: "Will AI Replace Google Search?",
    status: "published",
    source: "wordpress",
    primaryTopic: "growth",
    category: "AI Visibility · Search",
    wordCount: 1000,
    internalLinks: 2,
    productHref: "/ai-visibility/",
    score: 68,
    action: "migrate",
    recommendation: "migrate",
    related: ["ai-search-vs-seo", "chatgpt-recommends"],
  },
  {
    id: "ai-search-vs-seo",
    slug: "ai-search-vs-traditional-seo",
    url: "/ai-search-vs-traditional-seo/",
    title: "AI Search vs Traditional SEO",
    status: "published",
    source: "wordpress",
    pillar: true,
    primaryTopic: "growth",
    category: "Search & SEO · AI Visibility",
    searchIntent: "informational",
    primaryKeyword: "AI search vs SEO",
    audience: ["SME", "real estate", "services"],
    wordCount: 1450,
    internalLinks: 3,
    productHref: "/seo/",
    productLabel: "DigitalGate SEO",
    productBlurb: "Technical SEO and AI Visibility on the connected website you run on DigitalGate.",
    thin: false,
    score: 71,
    action: "migrate",
    actionNotes: "Migrate to Gen 2; add /seo and /ai-visibility links; reduce generic RE padding; add definition blocks.",
    recommendation: "migrate",
    related: ["chatgpt-recommends", "local-seo-ai-age", "foundational-1"],
  },
  {
    id: "entity-seo-re",
    slug: "entity-seo-for-real-estate-agencies",
    url: "/entity-seo-for-real-estate-agencies",
    title: "Entity SEO for Real Estate Agencies",
    status: "published",
    source: "wordpress",
    primaryTopic: "growth",
    secondaryTopics: ["industry"],
    category: "SEO · Real Estate",
    wordCount: 1100,
    internalLinks: 2,
    productHref: "/seo/",
    score: 69,
    action: "consolidate",
    actionNotes: "Consider consolidating with ai-visibility-re — overlapping entity/AI RE intent.",
    recommendation: "consolidate",
    related: ["ai-visibility-re", "ai-search-vs-seo"],
  },
  {
    id: "chatgpt-vs-google-re",
    slug: "chatgpt-vs-google-for-real-estate-marketing",
    url: "/chatgpt-vs-google-for-real-estate-marketing",
    title: "ChatGPT vs Google for Real Estate Marketing",
    status: "published",
    source: "wordpress",
    primaryTopic: "growth",
    secondaryTopics: ["industry"],
    wordCount: 1000,
    internalLinks: 2,
    score: 65,
    action: "consolidate",
    recommendation: "consolidate",
    related: ["ai-search-vs-seo", "ai-visibility-re"],
  },
  {
    id: "ai-visibility-re",
    slug: "ai-visibility-for-real-estate-agencies",
    url: "/ai-visibility-for-real-estate-agencies",
    title: "AI Visibility for Real Estate Agencies",
    status: "published",
    source: "wordpress",
    pillar: false,
    primaryTopic: "growth",
    secondaryTopics: ["industry"],
    wordCount: 1200,
    internalLinks: 2,
    productHref: "/ai-visibility/",
    score: 73,
    action: "migrate",
    recommendation: "migrate",
    related: ["ai-visibility-framework", "entity-seo-re"],
  },
  {
    id: "ai-search-leads-re",
    slug: "why-ai-search-changes-lead-generation-for-real-estate-agencies",
    url: "/why-ai-search-changes-lead-generation-for-real-estate-agencies",
    title: "Why AI Search Changes Lead Generation for Real Estate Agencies",
    status: "published",
    source: "wordpress",
    primaryTopic: "growth",
    secondaryTopics: ["industry"],
    wordCount: 1100,
    internalLinks: 2,
    productHref: "/prospecting/",
    score: 68,
    action: "migrate",
    recommendation: "migrate",
    related: ["local-seo-vendor-leads", "ai-visibility-re"],
  },
  {
    id: "local-seo-vendor-leads",
    slug: "local-seo-real-estate-vendor-leads",
    url: "/local-seo-real-estate-vendor-leads",
    title: "How Local SEO Helps Real Estate Agents Generate Vendor Leads",
    status: "published",
    source: "wordpress",
    primaryTopic: "growth",
    secondaryTopics: ["industry"],
    wordCount: 1200,
    internalLinks: 2,
    productHref: "/seo/",
    score: 70,
    action: "migrate",
    recommendation: "migrate",
    related: ["local-seo-ai-age", "appraisal-magnet"],
  },
  {
    id: "local-seo-ai-age",
    slug: "local-seo-in-the-age-of-ai-search",
    url: "/local-seo-in-the-age-of-ai-search",
    title: "Local SEO in the Age of AI Search",
    status: "published",
    source: "wordpress",
    primaryTopic: "growth",
    wordCount: 1100,
    internalLinks: 2,
    productHref: "/seo/",
    score: 72,
    action: "migrate",
    recommendation: "migrate",
    related: ["ai-search-vs-seo", "local-seo-vendor-leads"],
  },
];

export function insightById(id) {
  return INSIGHTS.find((i) => i.id === id);
}

export function relatedInsights(ids, limit = 4) {
  return ids
    .map((id) => insightById(id))
    .filter(Boolean)
    .slice(0, limit);
}

export function pillars() {
  return INSIGHTS.filter((i) => i.pillar);
}

export function byTopic(topicId) {
  return INSIGHTS.filter((i) => i.primaryTopic === topicId || i.secondaryTopics?.includes(topicId));
}

/** Topic cluster map for editorial planning */
export const TOPIC_CLUSTERS = [
  {
    pillar: "foundational-1",
    supporting: [
      "foundational-2",
      "business-brain",
      "ai-search-vs-seo",
      "chatgpt-recommends",
    ],
    products: ["/", "/business-brain/", "/growth/"],
    industries: ["/apps/industry/property/"],
  },
  {
    pillar: "ai-search-vs-seo",
    supporting: ["chatgpt-recommends", "gemini-local", "local-seo-ai-age", "will-ai-replace-google"],
    products: ["/seo/", "/ai-visibility/"],
    industries: [],
  },
  {
    pillar: "ai-visibility-framework",
    supporting: ["ai-visibility-re", "entity-seo-re", "chatgpt-vs-google-re"],
    products: ["/ai-visibility/", "/apps/industry/property/"],
    industries: ["/real-estate/ai-visibility/"],
  },
];
